# -*- coding: utf-8 -*-
"""088HvA GSE85718 — NMN Aging Microarray Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kDKdZ0Cm8KgxXIUkfJC3PHl2o5uMEH1

# GSE85718 — NMN Aging Microarray Pipeline
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q --upgrade "numpy>=2.2,<2.4" "scipy>=1.14,<1.18" \
    GEOparse gseapy statsmodels scanpy seaborn adjustText

# -*- coding: utf-8 -*-
"""
GSE85718 — NMN Aging Microarray Pipeline (Colab-ready)  [DEBUGGED v2]
=====================================================================
Long-term NMN administration vs. aging in mouse metabolic tissues.
Platform : Illumina MouseRef-8 v2.0 expression beadchip (GPL6885)
Design   : 3 tissues x 2 ages (6M/12M) x 2 treatments (Control/NMN) x 4 reps = 48

Core question: does NMN PREVENT age-associated transcriptional change?
  -> tested via the age:treatment INTERACTION term, per tissue.

FIXES vs v1
-----------
1. vectorized_ols: zero-residual-variance genes produced inf/NaN t -> NaN p.
   A single NaN made statsmodels BH return an ALL-NaN FDR vector, so every
   "FDR<0.05" count was 0 and rescue silently used the relaxed nominal-p rule.
   -> safe division, non-estimable genes get t=0 / p=1, and bh_fdr() is NaN-proof.
2. Normalization: per-sample quantile_transform(output_distribution="normal")
   clips at norm.ppf(1e-7) = +/-5.199. That ceiling generated the fake +/-5
   coefficients (Olfr*, Rik, V1r* background probes). -> quantile-normalize to a
   reference distribution, keeping LOG2 units (coefs = log2 fold-change).
3. NEW per-tissue expression/background filter before DE (removes on/off noise).
4. GSEA now ranks by the interaction t-statistic (fewer ties, proper weighting).
5. Artifact flagging + group-mean sanity tables in the report.
6. `import subprocess` (final cell crashed with NameError).
"""

# ============================================================
# 0. Install dependencies / imports
# ============================================================
# !pip -q install GEOparse gseapy statsmodels scikit-learn seaborn

import os, re, glob, warnings, textwrap, datetime, subprocess   # FIX: subprocess
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.preprocessing import quantile_transform
from statsmodels.stats.multitest import multipletests
import matplotlib
matplotlib.use("Agg") if os.environ.get("MPLBACKEND") == "Agg" else None
import matplotlib.pyplot as plt
import seaborn as sns
import GEOparse
warnings.filterwarnings("ignore")

import scipy, sklearn
print("numpy", np.__version__, "| scipy", scipy.__version__,
      "| pandas", pd.__version__, "| sklearn", sklearn.__version__)

# ============================================================
# 0b. CONFIG — the knobs you are meant to tune
# ============================================================
GSE_ID = "GSE85718"
WORK   = "/content/GSE85718"

NORM_METHOD   = "quantile_ref"   # "quantile_ref" (recommended) | "legacy_normal"
                                 # legacy_normal reproduces the buggy v1 scale

# --- per-tissue expression filter (applied BEFORE the model) ---
BG_QUANTILE   = 0.25   # background level = this quantile of all values in tissue
MIN_FRAC_ABV  = 0.50   # gene must exceed background in >= this fraction of samples
MIN_IQR       = 0.10   # log2 units; drops flat/undetected probes
MIN_VAR       = 1e-8   # numerical guard (non-estimable genes)

# --- rescue-gene criteria ---
STRICT = dict(fdr_age=0.05, fdr_int=0.10, min_abs_age=0.20, min_rescue_frac=0.30)
RELAX  = dict(p_age=0.05,   p_int=0.05,   min_abs_age=0.20, min_rescue_frac=0.30)
MIN_RESCUE_N  = 15     # below this, fall back to RELAX (and say so loudly)

TISSUES = ["Skeletal_muscle", "Liver", "WAT"]

# ============================================================
# 1. Workspace
# ============================================================
os.makedirs(WORK, exist_ok=True)
os.chdir(WORK)
for d in ["raw", "results", "results/DE", "results/genelists",
          "results/GSEA", "results/plots", "results/QC"]:
    os.makedirs(d, exist_ok=True)
print(">>> Workspace:", WORK)

RUN_LOG, WARNINGS_LOG = [], []
def log(msg):
    print(msg); RUN_LOG.append(str(msg))
def warn(msg):
    m = "!! " + str(msg)
    print(m); RUN_LOG.append(m); WARNINGS_LOG.append(str(msg))

# ============================================================
# 2. Download + parse SOFT family file
# ============================================================
log(f">>> Downloading & parsing {GSE_ID} (SOFT family file)...")
gse = GEOparse.get_GEO(geo=GSE_ID, destdir="raw", silent=True)

expr_probe = gse.pivot_samples("VALUE").apply(pd.to_numeric, errors="coerce")
log(">>> Raw probe matrix: " + str(expr_probe.shape))

# FIX: handle missing values before any sort/rank-based normalization
n_all_nan = int(expr_probe.isna().all(axis=1).sum())
expr_probe = expr_probe.loc[~expr_probe.isna().all(axis=1)]
frac_nan = expr_probe.isna().mean(axis=1)
n_drop_nan = int((frac_nan > 0.20).sum())
expr_probe = expr_probe.loc[frac_nan <= 0.20]
if expr_probe.isna().any().any():
    expr_probe = expr_probe.T.fillna(expr_probe.mean(axis=1)).T   # row-mean impute
if n_all_nan or n_drop_nan:
    log(f">>> NaN handling: dropped {n_all_nan} all-NaN probes, "
        f"{n_drop_nan} probes with >20% NaN, row-mean imputed the rest.")

gpl = list(gse.gpls.values())[0]
ann = gpl.table.copy()
id_col  = "ID" if "ID" in ann.columns else ann.columns[0]
sym_col = next((c for c in ["Symbol", "ILMN_Gene", "Gene_symbol", "GENE_SYMBOL"]
                if c in ann.columns), None)
assert sym_col is not None, f"No symbol column in GPL table: {list(ann.columns)}"
probe2sym = ann.set_index(id_col)[sym_col].astype(str).to_dict()
log(f">>> Annotation columns used: ID='{id_col}', Symbol='{sym_col}'")
PLATFORM_NAME = getattr(gpl, "name", "GPL6885")

# ============================================================
# 3. Metadata from sample titles
# ============================================================
rows = []
for gsm_name, gsm in gse.gsms.items():
    title = gsm.metadata["title"][0]; t = title.lower()
    tissue = ("Skeletal_muscle" if "muscle" in t else
              "Liver"           if "liver"  in t else
              "WAT"             if "wat"    in t else None)
    treatment = "NMN" if "nmn" in t else ("Control" if "control" in t else None)
    age = ("6M" if re.search(r"\b6m\b", t) else "12M" if re.search(r"\b12m\b", t) else None)
    rep = re.search(r"rep\s*(\d+)", t)
    rows.append(dict(sample_id=gsm_name, title=title, tissue=tissue,
                     treatment=treatment, age=age,
                     rep=int(rep.group(1)) if rep else np.nan))

meta = pd.DataFrame(rows).set_index("sample_id").loc[expr_probe.columns]
meta["age_num"]   = meta["age"].map({"6M": 0, "12M": 1})
meta["treat_num"] = meta["treatment"].map({"Control": 0, "NMN": 1})
meta["group"]     = meta["tissue"] + "_" + meta["treatment"] + "_" + meta["age"]
assert meta[["tissue", "treatment", "age"]].isna().sum().sum() == 0, "title parse failed"

log(">>> Sample design table:")
design_counts = meta.groupby(["tissue", "age", "treatment"]).size()
log(design_counts.to_string())
meta.to_csv("results/metadata_GSE85718.csv")

# ============================================================
# 4. Collapse probes -> genes (highest-mean probe per symbol)
# ============================================================
sym = pd.Series(expr_probe.index.map(probe2sym), index=expr_probe.index)
keep = sym.notna() & ~sym.isin(["nan", "NA", "None", "", "---"])
expr_g = expr_probe.loc[keep].copy()
expr_g["__sym__"]  = sym[keep].values
expr_g["__mean__"] = expr_g.drop(columns="__sym__").mean(axis=1)
n_probes_in = expr_probe.shape[0]
expr_g = (expr_g.sort_values("__mean__", ascending=False)
                .drop_duplicates("__sym__")
                .set_index("__sym__").drop(columns="__mean__"))
expr_g.index.name = "gene"
log(f">>> Gene-level matrix (probes collapsed): {expr_g.shape} (from {n_probes_in} probes)")

# ============================================================
# 5. Normalization  (FIX: keep log2 scale, no tail saturation)
# ============================================================
mat = expr_g.copy()
q = np.nanpercentile(mat.values, [0, 1, 50, 99, 100])
log(f">>> Value distribution before transform: min={q[0]:.2f} p1={q[1]:.2f} "
    f"median={q[2]:.2f} p99={q[3]:.2f} max={q[4]:.2f}")

if np.nanmax(mat.values) > 100:
    mat = np.log2(mat.clip(lower=0) + 1)
    LOG_NOTE = "log2(x+1) applied (values looked linear)"
    log(">>> Applied log2 transform (data looked linear).")
else:
    LOG_NOTE = "log2 skipped (values already on a compressed/log scale)"
    log(">>> Skipped log2 (data already on a compressed/log scale).")

def quantile_normalize_ref(df):
    """Classic quantile normalization: ranks -> mean-of-sorted reference.
    Keeps the original (log2) units, so coefficients are log2 fold-changes,
    and introduces NO tail clipping."""
    V = df.values.astype(float)
    n, m = V.shape
    ref = np.sort(V, axis=0).mean(axis=1)          # reference distribution
    xs  = np.arange(1, n + 1, dtype=float)
    out = np.empty_like(V)
    for j in range(m):
        r = stats.rankdata(V[:, j], method="average")
        out[:, j] = np.interp(r, xs, ref)
    return pd.DataFrame(out, index=df.index, columns=df.columns)

if NORM_METHOD == "quantile_ref":
    norm = quantile_normalize_ref(mat)
    NORM_NOTE = (f"{LOG_NOTE}; then quantile normalization to a common reference "
                 f"distribution (mean of sorted values). Units = log2 intensity, "
                 f"so model coefficients are log2 fold-changes.")
else:
    norm = pd.DataFrame(
        quantile_transform(mat.values, axis=0, output_distribution="normal", copy=True),
        index=mat.index, columns=mat.columns)
    NORM_NOTE = (f"{LOG_NOTE}; then per-sample quantile_transform to a normal "
                 f"distribution (LEGACY: saturates at +/-5.199).")
    warn("NORM_METHOD='legacy_normal' reproduces the v1 tail-clipping artifact.")

# saturation diagnostic (should be 0 for quantile_ref)
SAT = float(norm.abs().values.max())
n_sat = int((norm.abs().values > 5.19).sum())
log(f">=  Normalization: {NORM_METHOD} | max |value| = {SAT:.3f} | "
    f"values beyond +/-5.19 = {n_sat}")
if n_sat > 0:
    warn(f"{n_sat} values sit at the normal-transform clip bound (+/-5.199) — "
         f"these produce fake |coef| ~ 5-7. Use NORM_METHOD='quantile_ref'.")
norm.to_csv("results/normalized_expression.tsv.gz", sep="\t")
log(">>> Normalized matrix: " + str(norm.shape))

# ============================================================
# 6. NEW: per-tissue expression / background filter
# ============================================================
def tissue_ids(tissue):
    return meta.index[meta.tissue == tissue]

def expressed_mask(tissue, bg_q=BG_QUANTILE, min_frac=MIN_FRAC_ABV,
                   min_iqr=MIN_IQR, min_var=MIN_VAR, verbose=True):
    """Drop background / flat probes in this tissue (MouseRef-8 is full of them)."""
    Y   = norm.loc[:, tissue_ids(tissue)]
    bg  = float(np.quantile(Y.values, bg_q))
    frac_above = (Y > bg).mean(axis=1)
    iqr = Y.quantile(0.75, axis=1) - Y.quantile(0.25, axis=1)
    var = Y.var(axis=1)
    mask = (frac_above >= min_frac) & (iqr >= min_iqr) & (var > min_var)
    if verbose:
        log(f"    filter[{tissue}]: bg(q{bg_q:.2f})={bg:.3f} | "
            f"above-bg {int((frac_above >= min_frac).sum())} | "
            f"IQR>={min_iqr} {int((iqr >= min_iqr).sum())} | "
            f"kept {int(mask.sum())}/{len(mask)}")
    return mask, bg

FILTER_STATS = {}
log(">>> Applying per-tissue expression filter:")
masks = {}
for t in TISSUES:
    m, bg = expressed_mask(t)
    masks[t] = m
    FILTER_STATS[t] = dict(kept=int(m.sum()), total=int(len(m)), background=bg)
    if not (6000 <= m.sum() <= 15000):
        warn(f"{t}: {int(m.sum())} genes survive the filter — expected roughly "
             f"8k-12k of {len(m)}. Tune MIN_IQR / MIN_FRAC_ABV / BG_QUANTILE.")

# ============================================================
# 7. Vectorized per-tissue DE:  ~ age * treatment   (FIX: NaN-safe)
# ============================================================
def vectorized_ols(Y, X, min_var=MIN_VAR):
    """Y: genes x n ; X: n x p -> beta, se, t, p, estimable  (all NaN-free)."""
    n, p = X.shape
    XtX_inv = np.linalg.pinv(X.T @ X)          # pinv: tolerates rank deficiency
    beta  = Y @ X @ XtX_inv                    # genes x p
    resid = Y - beta @ X.T
    dof   = n - p
    sigma2 = (resid ** 2).sum(axis=1) / dof
    sigma2 = np.maximum(sigma2, 0.0)
    se = np.sqrt(np.outer(sigma2, np.diag(XtX_inv)))
    with np.errstate(divide="ignore", invalid="ignore"):
        tvals = np.divide(beta, se, out=np.zeros_like(beta), where=(se > 0))
    tvals = np.where(np.isfinite(tvals), tvals, 0.0)
    estimable = sigma2 > min_var               # zero-variance / perfect fit
    tvals[~estimable, :] = 0.0                 # -> p = 1, never NaN
    pvals = 2 * stats.t.sf(np.abs(tvals), dof)
    pvals = np.clip(np.nan_to_num(pvals, nan=1.0), 0.0, 1.0)
    return beta, se, tvals, pvals, estimable

def bh_fdr(p):
    """NaN-proof Benjamini-Hochberg. statsmodels returns ALL-NaN if any p is NaN."""
    p = np.asarray(p, dtype=float)
    out = np.ones(p.shape, dtype=float)
    ok = np.isfinite(p)
    if ok.any():
        out[ok] = multipletests(p[ok], method="fdr_bh")[1]
    return out

def run_tissue_de(tissue):
    sub   = meta[meta.tissue == tissue]
    genes = norm.index[masks[tissue]]                  # NEW: filtered gene space
    Y = norm.loc[genes, sub.index].values
    a = sub["age_num"].values.astype(float)
    g = sub["treat_num"].values.astype(float)
    X = np.column_stack([np.ones_like(a), a, g, a * g])
    beta, se, tv, pv, est = vectorized_ols(Y, X)

    de = pd.DataFrame({
        "gene":              genes,
        "coef_age_Control":  beta[:, 1], "t_age_Control": tv[:, 1], "p_age_Control": pv[:, 1],
        "coef_NMN_at6M":     beta[:, 2], "t_NMN_at6M":    tv[:, 2], "p_NMN_at6M":    pv[:, 2],
        "coef_interaction":  beta[:, 3], "t_interaction": tv[:, 3], "p_interaction": pv[:, 3],
        "estimable":         est,
        "mean_expr":         norm.loc[genes, sub.index].mean(axis=1).values,
    })
    for tag in ["age_Control", "NMN_at6M", "interaction"]:
        de[f"fdr_{tag}"] = bh_fdr(de[f"p_{tag}"])      # FIX
    n_bad = int((~de.estimable).sum())
    if n_bad:
        log(f"    {tissue}: {n_bad} non-estimable genes (zero residual variance) "
            f"forced to p=1 instead of NaN.")
    de = de.sort_values("p_interaction").reset_index(drop=True)
    de.to_csv(f"results/DE/DE_Interaction_{tissue}.tsv", sep="\t", index=False)
    return de

de_results, de_counts = {}, {}
for t in TISSUES:
    d = de_results[t] = run_tissue_de(t)
    # FIX: assert the failure mode can never come back silently
    for tag in ["age_Control", "NMN_at6M", "interaction"]:
        assert d[f"fdr_{tag}"].notna().all(), f"NaN FDR reappeared in {t}/{tag}"
    de_counts[t] = dict(
        n_tested=len(d),
        age_Control=int((d.fdr_age_Control < 0.05).sum()),
        NMN_at6M   =int((d.fdr_NMN_at6M   < 0.05).sum()),
        interaction=int((d.fdr_interaction < 0.05).sum()),
        min_fdr_age=float(d.fdr_age_Control.min()),
        min_fdr_int=float(d.fdr_interaction.min()))
    log(f">>> {t:16s} | tested {len(d):6d} | sig age(Control) FDR<0.05: "
        f"{de_counts[t]['age_Control']:5d} | sig NMN@6M: {de_counts[t]['NMN_at6M']:5d}"
        f" | sig interaction: {de_counts[t]['interaction']:5d}"
        f"   (min FDR: age={de_counts[t]['min_fdr_age']:.3g}, "
        f"int={de_counts[t]['min_fdr_int']:.3g})")

# ============================================================
# 8. Artifact flagging + group means (on/off background detector)
# ============================================================
GROUP_ORDER = ["Control_6M", "Control_12M", "NMN_6M", "NMN_12M"]

def group_mean_table(tissue, genes):
    sub = meta[meta.tissue == tissue]
    cols = {}
    for label in GROUP_ORDER:
        tr, ag = label.split("_")
        ids = sub[(sub.treatment == tr) & (sub.age == ag)].index
        cols[label] = norm.loc[genes, ids].mean(axis=1)
    return pd.DataFrame(cols)

def artifact_flags(tissue, genes):
    """Flag on/off-background behaviour: big between-group jump with ~no
    within-group scatter, and/or expression sitting at the background floor."""
    sub = meta[meta.tissue == tissue]
    Y   = norm.loc[genes, sub.index]
    bg  = FILTER_STATS[tissue]["background"]
    within_sd = []
    for label in GROUP_ORDER:
        tr, ag = label.split("_")
        ids = sub[(sub.treatment == tr) & (sub.age == ag)].index
        within_sd.append(Y[ids].std(axis=1))
    pooled_sd = pd.concat(within_sd, axis=1).mean(axis=1)
    G = group_mean_table(tissue, genes)
    span = G.max(axis=1) - G.min(axis=1)
    onoff = (span > 6 * (pooled_sd + 1e-3)) & (G.min(axis=1) <= bg)
    low   = Y.median(axis=1) <= bg
    flags = np.where(onoff, "ON_OFF_BACKGROUND",
             np.where(low, "LOW_EXPRESSED", ""))
    return pd.Series(flags, index=genes)

# ============================================================
# 9. NMN-rescue gene sets  (strict first, relaxed only as fallback)
# ============================================================
def rescue_select(de, mode):
    d = de.copy()
    # positive rescue fraction == interaction opposes the aging slope
    with np.errstate(divide="ignore", invalid="ignore"):
        d["rescue_frac"] = -d.coef_interaction / d.coef_age_Control.replace(0, np.nan)
    d["rescue_frac"] = d["rescue_frac"].fillna(0.0)
    if mode == "strict":
        c = STRICT
        sel = ((d.fdr_age_Control < c["fdr_age"]) & (d.fdr_interaction < c["fdr_int"]))
    else:
        c = RELAX
        sel = ((d.p_age_Control < c["p_age"]) & (d.p_interaction < c["p_int"]))
    sel &= (d.coef_age_Control.abs() >= c["min_abs_age"])
    sel &= (d.rescue_frac >= c["min_rescue_frac"])
    return d[sel].sort_values("p_interaction")

rescue, rescue_mode, rescue_counts = {}, {}, {}
for t in TISSUES:
    de = de_results[t]
    r_strict = rescue_select(de, "strict")
    r_relax  = rescue_select(de, "relaxed")
    rescue_counts[t] = dict(strict=len(r_strict), relaxed=len(r_relax))
    if len(r_strict) >= MIN_RESCUE_N:
        r, mode = r_strict, ("strict (FDR_age<%.2f & FDR_int<%.2f & |age|>=%.2f "
                             "& rescue_frac>=%.2f)" % (STRICT["fdr_age"], STRICT["fdr_int"],
                             STRICT["min_abs_age"], STRICT["min_rescue_frac"]))
    else:
        r, mode = r_relax, ("RELAXED / NOT FDR-CONTROLLED (nominal p_age<%.2f & "
                            "p_int<%.2f & |age|>=%.2f & rescue_frac>=%.2f)" %
                            (RELAX["p_age"], RELAX["p_int"], RELAX["min_abs_age"],
                             RELAX["min_rescue_frac"]))
        warn(f"{t}: only {len(r_strict)} strict rescue genes -> falling back to "
             f"nominal-p list ({len(r_relax)} genes). HYPOTHESIS-GENERATING ONLY.")
    r = r.copy()
    r["artifact_flag"] = artifact_flags(t, r.gene.tolist()).values if len(r) else []
    n_art = int((r.artifact_flag != "").sum()) if len(r) else 0
    if n_art:
        log(f"    {t}: {n_art}/{len(r)} rescue genes carry an artifact flag "
            f"(ON_OFF_BACKGROUND / LOW_EXPRESSED).")
    rescue[t], rescue_mode[t] = r, mode
    r.to_csv(f"results/genelists/NMN_Rescue_Genes_{t}.tsv", sep="\t", index=False)
    log(f">>> {t:16s} | NMN-rescue genes: {len(r):4d}  [{mode}]")

# ============================================================
# 10. Gene-list + GMT exports (clean genes only)
# ============================================================
def export_lists(tissue):
    de = de_results[tissue]
    de[de.fdr_interaction < 0.05].to_csv(
        f"results/DE/SigInteraction_{tissue}.tsv", sep="\t", index=False)
    r = rescue[tissue]
    clean = r[r.artifact_flag == ""] if len(r) else r
    genes = clean["gene"].dropna().astype(str).str.upper().unique().tolist()
    with open(f"results/genelists/GeneList_NMN_Rescue_{tissue}.txt", "w") as f:
        f.write("\n".join(genes))
    with open(f"results/genelists/Aging_NMN_Rescue_{tissue}.gmt", "w") as f:
        f.write(f"Aging_NMN_Rescue_{tissue}\t"
                f"Age-related change prevented by NMN in {tissue} "
                f"(artifact-flagged genes removed)\t" + "\t".join(genes) + "\n")
    return genes

clean_lists = {t: export_lists(t) for t in TISSUES}
log(">>> Gene lists and GMT files written to results/genelists/ "
    "(artifact-flagged genes excluded from the .txt/.gmt exports)")

# ============================================================
# 11. GSEA on the interaction t-statistic
# ============================================================
import gseapy as gp
GENE_SETS = ["MSigDB_Hallmark_2020", "KEGG_2019_Mouse", "GO_Biological_Process_2021"]

def run_gsea(tissue):
    de = de_results[tissue].dropna(subset=["t_interaction"])
    rnk = (de.assign(gene=de.gene.str.upper())[["gene", "t_interaction"]]
             .groupby("gene", as_index=False).mean()
             .sort_values("t_interaction", ascending=False))
    ties = 1 - rnk.t_interaction.nunique() / len(rnk)
    log(f"    GSEA {tissue}: {len(rnk)} genes ranked by interaction t "
        f"({ties*100:.2f}% tied values)")
    try:
        res = gp.prerank(rnk=rnk, gene_sets=GENE_SETS, permutation_num=1000,
                         min_size=10, max_size=500, outdir=f"results/GSEA/{tissue}",
                         seed=42, no_plot=True, verbose=False, threads=4)
        res.res2d.to_csv(f"results/GSEA/GSEA_{tissue}.tsv", sep="\t", index=False)
        log(f">>> GSEA {tissue}: {len(res.res2d)} terms tested")
        return res
    except Exception as e:
        warn(f"GSEA {tissue} skipped (Enrichr/network issue): {e}")
        return None

gsea_results = {t: run_gsea(t) for t in TISSUES}

# ============================================================
# 12. Plots
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for ax, t in zip(axes, TISSUES):
    d = de_results[t]
    x = d.coef_interaction
    y = -np.log10(d.p_interaction.clip(lower=1e-300))
    sig = d.fdr_interaction < 0.05
    ax.scatter(x[~sig], y[~sig], s=6, color="lightgray")
    ax.scatter(x[sig],  y[sig],  s=12, color="crimson")
    ax.axhline(-np.log10(0.05), ls="--", lw=0.8, color="k")
    ax.set_title(f"{t}\nInteraction (NMN x Age) — {int(sig.sum())} @ FDR<0.05")
    ax.set_xlabel("interaction coefficient (log2)"); ax.set_ylabel("-log10(p)")
plt.tight_layout(); plt.savefig("results/plots/volcano_interaction.png", dpi=150); plt.show()

def zscored_groups(tissue, genes):
    M = group_mean_table(tissue, genes)
    return M.sub(M.mean(1), axis=0).div(M.std(1).replace(0, 1), axis=0)

for t in TISSUES:
    r = rescue[t]; r = r[r.artifact_flag == ""]
    genes = r["gene"].head(40).tolist()
    if len(genes) < 2:
        log(f">>> {t}: too few clean rescue genes for a heatmap."); continue
    Z = zscored_groups(t, genes)
    plt.figure(figsize=(6, max(4, len(genes) * 0.22)))
    sns.heatmap(Z, cmap="RdBu_r", center=0, yticklabels=True,
                cbar_kws={"label": "z-score across groups"})
    plt.title(f"NMN-rescue genes (top {len(genes)}, artifact-filtered) — {t}")
    plt.tight_layout(); plt.savefig(f"results/plots/rescue_heatmap_{t}.png", dpi=150); plt.show()

# QC: distribution check after normalization
plt.figure(figsize=(12, 4))
sns.boxplot(data=pd.DataFrame(norm.values, columns=norm.columns), fliersize=0.5)
plt.xticks(rotation=90, fontsize=5); plt.ylabel("normalized log2")
plt.title(f"Per-sample distributions after {NORM_METHOD}")
plt.tight_layout(); plt.savefig("results/QC/sample_boxplots.png", dpi=150); plt.close()

# ============================================================
# 13. Cross-tissue overlap
# ============================================================
rescue_sets = {t: set(pd.Series(clean_lists[t])) for t in TISSUES}
overlap = pd.DataFrame([[len(rescue_sets[a] & rescue_sets[b]) for b in TISSUES]
                        for a in TISSUES], index=TISSUES, columns=TISSUES)
log(">>> NMN-rescue gene overlap across tissues (clean lists):")
log(overlap.to_string())
overlap.to_csv("results/genelists/rescue_overlap_matrix.csv")

# ============================================================
# 14. Detailed summary report
# ============================================================
SUMMARY_PATH = "results/SUMMARY_REPORT.txt"
def hr(c="=", n=78): return c * n
SCI = lambda c: bool(re.search(r"(^p_|^p$|pval|p-val|fdr)", str(c).lower()))

def fmt_top_table(df, cols, n=20, floatfmt="{:+.3f}", trunc=70):
    sub = df[cols].head(n).copy()
    def cell(c, v):
        if isinstance(v, (bool, np.bool_)):        return str(bool(v))
        if isinstance(v, (int, np.integer)):       return str(int(v))
        if isinstance(v, (float, np.floating)):
            if not np.isfinite(v):                 return "NA"
            return f"{v:.3e}" if SCI(c) else floatfmt.format(v)
        return str(v)[:trunc]
    if len(sub) == 0:
        return "(no rows)"
    body = {c: [cell(c, v) for v in sub[c]] for c in cols}
    w = {c: max([len(str(c))] + [len(x) for x in body[c]]) for c in cols}
    lines = ["  ".join(str(c).ljust(w[c]) for c in cols),
             "  ".join("-" * w[c] for c in cols)]
    for i in range(len(sub)):
        lines.append("  ".join(body[c][i].ljust(w[c]) for c in cols))
    return "\n".join(lines)

def top_gsea(res, n=10):
    if res is None or getattr(res, "res2d", None) is None: return None
    df = res.res2d.copy(); ren = {}
    for c in df.columns:
        lc = c.lower()
        if lc == "term": ren[c] = "Term"
        elif lc == "nes": ren[c] = "NES"
        elif lc in ("fdr q-val", "fdr", "fdr_q-val"): ren[c] = "FDR"
        elif lc in ("nom p-val", "pval", "p-value"): ren[c] = "pval"
    df = df.rename(columns=ren)
    for k, v in [("Term", ""), ("NES", np.nan), ("FDR", np.nan), ("pval", np.nan)]:
        if k not in df.columns: df[k] = v
    for k in ["NES", "FDR", "pval"]:
        df[k] = pd.to_numeric(df[k], errors="coerce")
    df = df.dropna(subset=["NES"])
    return (df.sort_values("NES", ascending=False).head(n),
            df.sort_values("NES", ascending=True).head(n))

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
S = [hr("#"),
     "#  GSE85718 — NMN ANTI-AGING TRANSCRIPTOMICS : DETAILED SUMMARY REPORT (v2)",
     hr("#"),
     f"Generated         : {now}",
     f"Workspace         : {os.path.abspath(WORK)}",
     f"Pipeline version  : v2 (NaN-FDR fix, reference quantile norm, expression filter)",
     ""]

S += [hr(), "0. VALIDITY / DIAGNOSTICS", hr()]
S.append("FDR vectors contain no NaN (asserted per tissue and per term).")
S.append(f"Normalization    : {NORM_METHOD} | max |value| {SAT:.3f} | "
         f"clip-bound values {n_sat} (must be 0 for quantile_ref)")
S.append("Genes tested after per-tissue expression filter:")
for t in TISSUES:
    fs = FILTER_STATS[t]
    S.append(f"  {t:16s}: {fs['kept']:6d} / {fs['total']} kept "
             f"(background level {fs['background']:.3f})")
S.append("")
S.append("Rescue-list mode per tissue (strict = FDR-controlled):")
for t in TISSUES:
    S.append(f"  {t:16s}: strict={rescue_counts[t]['strict']:5d}  "
             f"relaxed={rescue_counts[t]['relaxed']:5d}  -> used: {rescue_mode[t]}")
S.append("")
if WARNINGS_LOG:
    S.append("WARNINGS RAISED IN THIS RUN:")
    S += [f"  - {w}" for w in WARNINGS_LOG]
else:
    S.append("No warnings raised.")
S.append("")

S += [hr(), "1. STUDY & EXPERIMENTAL DESIGN", hr(),
      textwrap.fill(
        "Series GSE85718 (Mills KF et al., Cell Metab 2016; PMID 28068222): "
        "12-month oral NMN administration (300 mg/kg/day) to chow-fed wild-type "
        "C57BL/6N mice during normal aging. NMN suppressed age-associated body "
        "weight gain, enhanced energy metabolism and insulin sensitivity, improved "
        "plasma lipids and eye function, and prevented age-associated gene "
        "expression changes in key metabolic organs.", width=78), "",
      f"Platform          : {PLATFORM_NAME} (Illumina MouseRef-8 v2.0 beadchip)",
      f"Samples           : {norm.shape[1]} total",
      "Factors           : tissue {Skeletal_muscle, Liver, WAT} x age {6M, 12M} x "
      "treatment {Control, NMN} x 4 reps", "",
      "Sample counts per cell:", design_counts.to_string(), ""]

S += [hr(), "2. PROCESSING & STATISTICAL MODEL", hr(),
      f"Probe->gene       : {n_probes_in} probes collapsed to {expr_g.shape[0]} genes "
      f"(highest-mean probe per symbol).",
      f"Normalization     : {NORM_NOTE}",
      f"Expression filter : per tissue, gene must exceed the q{BG_QUANTILE:.2f} background "
      f"in >={MIN_FRAC_ABV:.0%} of samples, with IQR >= {MIN_IQR} log2.",
      "Model (per tissue): expression ~ age * treatment",
      "  coef_age_Control : aging effect within the Control arm (treatment=0)",
      "  coef_NMN_at6M    : NMN effect at the young (6M) timepoint (age=0)",
      "  coef_interaction : age x treatment = does NMN MODIFY the aging slope?",
      "Non-estimable genes (zero residual variance) get t=0 / p=1, never NaN.",
      "Multiple testing  : Benjamini-Hochberg FDR per tissue & term (NaN-proof).", "",
      textwrap.fill("INTERPRETATION KEY: an 'NMN-rescue' candidate changes with age in "
        "Control AND has an interaction coefficient of opposite sign, with "
        f"rescue_frac = -coef_int/coef_age >= {STRICT['min_rescue_frac']} — i.e. NMN moves "
        "at least ~30% of the age shift back toward the young state.", width=78), ""]

S += [hr(), "3. DIFFERENTIAL-EXPRESSION OVERVIEW (FDR < 0.05)", hr()]
ov = pd.DataFrame(de_counts).T[["n_tested", "age_Control", "NMN_at6M", "interaction",
                                "min_fdr_age", "min_fdr_int"]]
ov.columns = ["Genes tested", "Age(Control)", "NMN@6M", "Interaction",
              "min FDR age", "min FDR int"]
S += [ov.to_string(), ""]

for t in TISSUES:
    d = de_results[t]; r = rescue[t]
    S += [hr(), f"4. TISSUE DETAIL — {t}", hr()]
    S.append("  (a) Top 20 AGE-associated genes in Control:")
    S.append(textwrap.indent(fmt_top_table(d.sort_values("p_age_Control"),
        ["gene", "mean_expr", "coef_age_Control", "p_age_Control", "fdr_age_Control"], 20), "      "))
    S.append("")
    S.append("  (b) Top 20 INTERACTION genes (NMN x Age):")
    S.append(textwrap.indent(fmt_top_table(d,
        ["gene", "mean_expr", "coef_age_Control", "coef_interaction",
         "p_interaction", "fdr_interaction"], 20), "      "))
    S.append("")
    S.append(f"  (c) NMN-RESCUE genes (n={len(r)}; mode: {rescue_mode[t]}):")
    if len(r):
        rr = r.copy()
        rr["age_dir"] = np.where(rr.coef_age_Control > 0, "UP_with_age", "DOWN_with_age")
        S.append(textwrap.indent(fmt_top_table(rr,
            ["gene", "age_dir", "coef_age_Control", "coef_interaction", "rescue_frac",
             "fdr_age_Control", "fdr_interaction", "artifact_flag"], min(len(rr), 200)), "      "))
        S.append("")
        S.append(f"      Of these, {int((r.coef_age_Control>0).sum())} rose with age "
                 f"(NMN lowers them) and {int((r.coef_age_Control<0).sum())} fell with age "
                 f"(NMN raises them). Artifact-flagged: {int((r.artifact_flag!='').sum())} "
                 f"(excluded from exported .txt/.gmt).")
    else:
        S.append("      (none passed the rescue criteria)")
    S.append("")
    S.append("  (d) SANITY CHECK — group means of the top 10 interaction genes:")
    g10 = d.gene.head(10).tolist()
    if g10:
        G = group_mean_table(t, g10).round(3)
        G["flag"] = artifact_flags(t, g10).values
        S.append(textwrap.indent(G.to_string(), "      "))
        S.append("      (identical background values in 3 groups + one spike = artifact)")
    S.append("")
    S.append("  (e) GSEA on the interaction t-statistic ranking:")
    tg = top_gsea(gsea_results.get(t), 10)
    if tg is None:
        S.append("      GSEA unavailable (network/Enrichr issue or no results).")
    else:
        up, down = tg
        S.append("      -- Positive NES (NMN raises old-age expression vs Control) --")
        S.append(textwrap.indent(fmt_top_table(up, ["Term", "NES", "pval", "FDR"], 10), "        "))
        S.append("")
        S.append("      -- Negative NES (NMN lowers old-age expression vs Control) --")
        S.append(textwrap.indent(fmt_top_table(down, ["Term", "NES", "pval", "FDR"], 10), "        "))
    S.append("")

S += [hr(), "5. CROSS-TISSUE INTEGRATION OF NMN-RESCUE GENES (clean lists)", hr(),
      "Pairwise overlap counts (diagonal = set size):", overlap.to_string(), ""]
shared_all = set.intersection(*rescue_sets.values()) if all(len(s) for s in rescue_sets.values()) else set()
S.append(f"Rescued in ALL three tissues ({len(shared_all)}): "
         + (", ".join(sorted(shared_all)) if shared_all else "none"))
for a in TISSUES:
    for b in TISSUES:
        if a < b:
            sh = sorted(rescue_sets[a] & rescue_sets[b])
            S.append(f"  {a} n {b} ({len(sh)}): " +
                     (", ".join(sh[:40]) + (" ..." if len(sh) > 40 else "") if sh else "none"))
S.append("")

S += [hr(), "6. KEY TAKEAWAYS", hr()]
if any(de_counts[t]["interaction"] > 0 for t in TISSUES):
    best = max(TISSUES, key=lambda t: de_counts[t]["interaction"])
    S.append(textwrap.fill(f"- Strongest FDR-controlled NMN x age interaction signal: {best} "
        f"({de_counts[best]['interaction']} genes at FDR<0.05).", width=78))
else:
    S.append(textwrap.fill("- NO gene reaches FDR<0.05 for the interaction term in any tissue. "
        "With n=4 per cell this is an expected power outcome. Any tissue ranking or "
        "'strongest signal' statement is therefore NOT supported by these data; the "
        "rescue lists below are nominal-p only.", width=78))
S += [textwrap.fill("- The interaction term operationalizes the paper's central claim: a "
        "significant interaction with sign opposite to the control aging effect is the "
        "formal signature of NMN preventing an age-related change.", width=78),
      textwrap.fill("- v1 of this pipeline reported all-NaN FDR (a single NaN p-value collapses "
        "Benjamini-Hochberg) and used a per-sample rank->normal transform that clips at "
        "+/-5.199; the resulting +/-5 'effects' on Olfr*/V1r*/Rik background probes were "
        "artifacts. Both are fixed here.", width=78),
      textwrap.fill("- GSEA Hallmark sets are human; mouse symbols were upper-cased as an "
        "ortholog proxy. KEGG_2019_Mouse and GO_BP_2021 are the more appropriate "
        "references. FDR > 0.25 terms should be treated as noise.", width=78), ""]

S += [hr(), "7. OUTPUT FILE MANIFEST", hr()]
for f in sorted(glob.glob("results/**/*", recursive=True)):
    if os.path.isfile(f):
        sz = os.path.getsize(f)
        h = f"{sz/1e6:.2f} MB" if sz > 1e6 else f"{sz/1e3:.1f} KB" if sz > 1e3 else f"{sz} B"
        S.append(f"  {f:55s} {h:>10s}")
S += ["", hr(), "8. RUN LOG (console trace)", hr()]
S += ["  " + ln for ln in RUN_LOG]
S += ["", hr("#"), "#  END OF REPORT", hr("#")]

with open(SUMMARY_PATH, "w") as fh:
    fh.write("\n".join(S) + "\n")

print("\n>>> Detailed summary written to:", os.path.abspath(SUMMARY_PATH))
print(">>> Preview (first 60 lines):\n"); print("\n".join(S[:60]))

# ============================================================
# 15. Final banner
# ============================================================
print("\n" + "=" * 60); print("DONE — GSE85718 NMN aging pipeline (v2)"); print("=" * 60)
print(textwrap.dedent(f"""
  Outputs under: {os.path.abspath('results')}
    SUMMARY_REPORT.txt                     <-- detailed all-in-one report
    metadata_GSE85718.csv
    normalized_expression.tsv.gz
    DE/DE_Interaction_<tissue>.tsv         (full per-gene stats, incl. t & FDR)
    DE/SigInteraction_<tissue>.tsv         (FDR<0.05 interaction)
    genelists/NMN_Rescue_Genes_<tissue>.tsv  (with rescue_frac + artifact_flag)
    genelists/GeneList_NMN_Rescue_<tissue>.txt   (artifact-filtered)
    genelists/Aging_NMN_Rescue_<tissue>.gmt      (artifact-filtered)
    genelists/rescue_overlap_matrix.csv
    GSEA/GSEA_<tissue>.tsv
    plots/volcano_interaction.png, plots/rescue_heatmap_<tissue>.png
    QC/sample_boxplots.png
"""))
subprocess.run("find results -maxdepth 2 -type f | sort", shell=True)   # FIX: imported

"""# Downstream Analysis"""

# -*- coding: utf-8 -*-
"""
GSE85718 — STAGE 2: Downstream Analysis of NMN-Rescue Gene Lists
================================================================
Consumes the outputs of the stage-1 pipeline:
    results/genelists/NMN_Rescue_Genes_<tissue>.tsv
    results/DE/DE_Interaction_<tissue>.tsv          (used for full-ranking GSEA)
    results/genelists/Aging_NMN_Rescue_<tissue>.gmt

Performs:
  1. Load & label rescue gene tables
  2. Effect-size filtering (noise reduction)
  3. High-confidence candidate selection (p & effect)
  4. Cross-tissue robustness (genes rescued in >= 2 tissues)
  5. Pathway-level insight:
        A. MitoCarta overlap (auto-download w/ fallback list)
        B. Prerank GSEA on interaction coefficient
  6. Visualizations (effect-size distributions, robustness, mito overlap)
  7. DOWNSTREAM_SUMMARY_REPORT.txt  (detailed all-in-one)
"""

# ============================================================
# 0. Setup
# ============================================================
import subprocess
subprocess.run("pip -q install gseapy seaborn", shell=True, check=False)

import os, glob, textwrap, datetime, warnings
from pathlib import Path
from functools import reduce
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings("ignore")

# --- paths (adjust if you ran stage 1 elsewhere) ---
WORK      = "/content/GSE85718"
if os.path.isdir(WORK):
    os.chdir(WORK)
RESULTS   = Path("results")
GENELISTS = RESULTS / "genelists"
DE_DIR    = RESULTS / "DE"
OUT       = RESULTS / "downstream"
for d in [OUT, OUT / "GSEA", OUT / "plots", OUT / "tables"]:
    d.mkdir(parents=True, exist_ok=True)

TISSUES = ["Skeletal_muscle", "Liver", "WAT"]

# --- tunable thresholds ---
EFFECT_THRESHOLD = 0.8     # |coef_interaction| cutoff for "large effect"
P_THRESHOLD      = 0.01    # p_interaction cutoff for high-confidence
MIN_TISSUES      = 2       # robustness: rescued in >= this many tissues

RUN_LOG = []
def log(msg):
    print(msg)
    RUN_LOG.append(str(msg))

log(">>> STAGE 2 downstream analysis")
log(">>> Working dir: " + os.path.abspath("."))

# ============================================================
# 1. Load & prepare the rescue gene tables
# ============================================================
def load_rescue(tissue):
    f = GENELISTS / f"NMN_Rescue_Genes_{tissue}.tsv"
    if not f.exists():
        log(f"!!! MISSING: {f} — run stage 1 first.")
        return pd.DataFrame()
    df = pd.read_csv(f, sep="\t")
    df["tissue"] = tissue
    # normalize gene symbols for cross-tissue matching
    df["gene"] = df["gene"].astype(str).str.upper().str.strip()
    return df

rescue = {t: load_rescue(t) for t in TISSUES}
for t in TISSUES:
    log(f">>> {t:16s} rescue genes loaded: {len(rescue[t])}")

all_genes = pd.concat([d for d in rescue.values() if len(d)], ignore_index=True)
if all_genes.empty:
    raise SystemExit("No rescue genes found — cannot continue. Run stage 1 first.")

# Ensure expected columns exist; create safe fallbacks if not.
for col in ["coef_interaction", "p_interaction", "coef_age_Control",
            "fdr_interaction", "fdr_age_Control"]:
    if col not in all_genes.columns:
        all_genes[col] = np.nan
        for t in TISSUES:
            if col not in rescue[t].columns and len(rescue[t]):
                rescue[t][col] = np.nan

# ============================================================
# 2. Effect-size filtering (noise reduction)
# ============================================================
def filter_by_effect_size(df, threshold=EFFECT_THRESHOLD):
    if df.empty:
        return df
    return df[df["coef_interaction"].abs() >= threshold].copy()

rescue_filt = {t: filter_by_effect_size(rescue[t]) for t in TISSUES}
log(f"\n>>> After |coef_interaction| >= {EFFECT_THRESHOLD} filter:")
for t in TISSUES:
    log(f"  {t:16s}: {len(rescue_filt[t]):4d} / {len(rescue[t]):4d} genes")
    if len(rescue_filt[t]):
        rescue_filt[t].to_csv(
            OUT / "tables" / f"EffectFiltered_{t}.tsv", sep="\t", index=False)

# ============================================================
# 3. High-confidence candidates (p AND effect)
# ============================================================
def get_high_confidence(df, p_threshold=P_THRESHOLD,
                        effect_threshold=EFFECT_THRESHOLD):
    if df.empty:
        return df
    sel = df[(df["p_interaction"] < p_threshold) &
             (df["coef_interaction"].abs() >= effect_threshold)]
    return sel.sort_values("p_interaction").copy()

high_conf = {t: get_high_confidence(rescue[t]) for t in TISSUES}
log(f"\n>>> High-confidence genes (p_int < {P_THRESHOLD} & "
    f"|coef_int| >= {EFFECT_THRESHOLD}):")
for t in TISSUES:
    log(f"  {t:16s}: {len(high_conf[t]):4d}")
    if len(high_conf[t]):
        high_conf[t].to_csv(
            OUT / "tables" / f"High_Confidence_{t}.tsv", sep="\t", index=False)

# ============================================================
# 4. Cross-tissue robustness (rescued in >= MIN_TISSUES)
# ============================================================
gene_counts = (all_genes.groupby("gene")["tissue"]
               .nunique().reset_index()
               .rename(columns={"tissue": "tissue_count"}))
robust_genes = gene_counts[gene_counts["tissue_count"] >= MIN_TISSUES]["gene"].tolist()
log(f"\n>>> Genes rescued in >= {MIN_TISSUES} tissues: {len(robust_genes)}")

robust_df = (all_genes[all_genes["gene"].isin(robust_genes)]
             .sort_values(["gene", "tissue"]))
robust_df.to_csv(OUT / "tables" / "Cross_Tissue_Robust_Rescue_Genes.tsv",
                 sep="\t", index=False)

# Per-gene robustness summary: direction consistency across tissues
def robustness_summary(df):
    out = []
    for g, sub in df.groupby("gene"):
        tissues = ", ".join(sorted(sub["tissue"]))
        # consistent if all interaction coefficients share a sign
        signs = np.sign(sub["coef_interaction"].dropna())
        consistent = (len(signs) > 0) and (signs.nunique() == 1)
        out.append({
            "gene": g,
            "n_tissues": sub["tissue"].nunique(),
            "tissues": tissues,
            "mean_coef_interaction": sub["coef_interaction"].mean(),
            "mean_coef_age_Control": sub["coef_age_Control"].mean(),
            "direction_consistent": consistent,
        })
    return pd.DataFrame(out).sort_values(
        ["n_tissues", "mean_coef_interaction"],
        ascending=[False, False]) if out else pd.DataFrame()

robust_detail = robustness_summary(robust_df)
if len(robust_detail):
    robust_detail.to_csv(OUT / "tables" / "Robust_Gene_Summary.tsv",
                         sep="\t", index=False)
genes_all3 = robust_detail[robust_detail.n_tissues == 3]["gene"].tolist() \
    if len(robust_detail) else []
log(f">>> Genes rescued in ALL 3 tissues: {len(genes_all3)} "
    + ("(" + ", ".join(genes_all3) + ")" if genes_all3 else ""))

# ============================================================
# 5A. Pathway-level: MitoCarta overlap
#     (auto-download mouse symbols; fall back to a curated mini-set)
# ============================================================
FALLBACK_MITO = {  # small curated OXPHOS / mito core (upper-cased mouse symbols)
    "NDUFA1","NDUFA2","NDUFA9","NDUFB8","NDUFS1","NDUFS3","NDUFV1","SDHA","SDHB",
    "UQCRC1","UQCRC2","CYC1","COX4I1","COX5A","COX5B","COX6A1","COX7A1","COX8B",
    "ATP5A1","ATP5B","ATP5C1","ATP5O","ATP5J","CS","IDH3A","SUCLA2","FH1","MDH2",
    "ACO2","OGDH","PDHA1","PDHB","DLAT","CPT1B","CPT2","ACADM","ACADL","ACADVL",
    "HADHA","HADHB","ECI1","SLC25A4","SLC25A20","TFAM","NRF1","PPARGC1A","ESRRA",
    "MFN1","MFN2","OPA1","DNM1L","PINK1","PRKN","SOD2","TFB1M","TFB2M","POLG",
    "MRPL12","MRPS12","TIMM23","TOMM20","VDAC1","VDAC2","CYCS","UCP2","UCP3",
}

def load_mitocarta():
    # 1) user-provided local file
    for cand in ["MitoCarta3.0_Mouse_Symbols.txt",
                 str(GENELISTS / "MitoCarta3.0_Mouse_Symbols.txt")]:
        if os.path.exists(cand):
            try:
                s = pd.read_csv(cand, header=None)[0].astype(str).str.upper()
                log(f">>> MitoCarta loaded from {cand}: {len(set(s))} symbols")
                return set(s), f"local:{cand}"
            except Exception as e:
                log(f">>> MitoCarta local read failed: {e}")
    # 2) try Enrichr 'Mitochondrial' library via gseapy as a proxy
    try:
        import gseapy as gp
        libs = gp.get_library(name="MitoCarta_2020", organism="Mouse")
        symbols = set()
        for v in libs.values():
            symbols |= {x.upper() for x in v}
        if symbols:
            log(f">>> MitoCarta proxy via Enrichr: {len(symbols)} symbols")
            return symbols, "enrichr:MitoCarta_2020"
    except Exception as e:
        log(f">>> Enrichr MitoCarta unavailable: {e}")
    # 3) fallback curated mini-set
    log(f">>> Using FALLBACK curated mito set ({len(FALLBACK_MITO)} symbols).")
    return set(FALLBACK_MITO), "fallback:curated_core"

mito_set, mito_source = load_mitocarta()

def mito_overlap(df, mito):
    if df.empty:
        return set()
    return set(df["gene"]) & mito

mito_hits = {t: mito_overlap(rescue[t], mito_set) for t in TISSUES}
log(f"\n>>> Mitochondrial overlap (source = {mito_source}):")
for t in TISSUES:
    log(f"  {t:16s}: {len(mito_hits[t]):3d} mito genes "
        + ("[" + ", ".join(sorted(mito_hits[t])[:12])
           + (" ..." if len(mito_hits[t]) > 12 else "") + "]"
           if mito_hits[t] else ""))

# hypergeometric enrichment of mito genes within each rescue list
from scipy.stats import hypergeom
def mito_enrich(df, mito, universe_n=20000):
    if df.empty:
        return np.nan, 0
    n_list = df["gene"].nunique()
    n_mito = len(mito)
    k = len(set(df["gene"]) & mito)
    # P(X >= k)
    p = hypergeom.sf(k - 1, universe_n, n_mito, n_list)
    return p, k

mito_enrich_res = {}
for t in TISSUES:
    p, k = mito_enrich(rescue[t], mito_set)
    mito_enrich_res[t] = {"k_mito": k, "n_genes": rescue[t]["gene"].nunique()
                          if len(rescue[t]) else 0, "hyper_p": p}
    log(f"  {t:16s}: hypergeometric p = {p:.3e} (k={k})")

# ============================================================
# 5B. Pathway-level: prerank GSEA on interaction coefficient
#     Uses FULL DE ranking if available (better than rescue-only).
# ============================================================
import gseapy as gp
GSEA_LIBS = ["MSigDB_Hallmark_2020", "KEGG_2019_Mouse",
             "GO_Biological_Process_2021"]

def load_full_ranking(tissue):
    f = DE_DIR / f"DE_Interaction_{tissue}.tsv"
    if f.exists():
        d = pd.read_csv(f, sep="\t")
        rnk = (d.assign(gene=d.gene.astype(str).str.upper())
                 [["gene", "coef_interaction"]]
                 .dropna()
                 .groupby("gene", as_index=False).mean()
                 .sort_values("coef_interaction", ascending=False))
        return rnk, "full_DE"
    # fallback: rank from rescue table only
    d = rescue[tissue]
    if d.empty:
        return None, None
    rnk = (d[["gene", "coef_interaction"]].dropna()
             .groupby("gene", as_index=False).mean()
             .sort_values("coef_interaction", ascending=False))
    return rnk, "rescue_only"

gsea_top = {}
for t in TISSUES:
    rnk, src = load_full_ranking(t)
    if rnk is None or len(rnk) < 15:
        log(f">>> GSEA {t}: insufficient ranking ({src}) — skipped.")
        gsea_top[t] = None
        continue
    try:
        res = gp.prerank(rnk=rnk, gene_sets=GSEA_LIBS,
                         permutation_num=1000, min_size=10, max_size=500,
                         outdir=str(OUT / "GSEA" / t), seed=42,
                         no_plot=True, verbose=False)
        res.res2d.to_csv(OUT / "GSEA" / f"GSEA_downstream_{t}.tsv",
                         sep="\t", index=False)
        gsea_top[t] = res
        log(f">>> GSEA {t} ({src}): {len(res.res2d)} terms")
    except Exception as e:
        log(f">>> GSEA {t} skipped: {e}")
        gsea_top[t] = None

def top_gsea_terms(res, n=10):
    if res is None or not hasattr(res, "res2d") or res.res2d is None:
        return None
    df = res.res2d.copy()
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc == "term": rename[c] = "Term"
        elif lc == "nes": rename[c] = "NES"
        elif lc in ("fdr q-val", "fdr", "fdr_q-val"): rename[c] = "FDR"
        elif lc in ("nom p-val", "pval", "p-value"): rename[c] = "pval"
    df = df.rename(columns=rename)
    for need, dflt in [("Term", ""), ("NES", np.nan),
                       ("FDR", np.nan), ("pval", np.nan)]:
        if need not in df.columns:
            df[need] = dflt
    for c in ["NES", "FDR", "pval"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["NES"])
    up   = df.sort_values("NES", ascending=False).head(n)
    down = df.sort_values("NES", ascending=True).head(n)
    return up, down

# ============================================================
# 6. Visualizations
# ============================================================
# 6a. Effect-size distribution by tissue
plt.figure(figsize=(10, 6))
sns.histplot(data=all_genes, x="coef_interaction", hue="tissue",
             bins=60, kde=True, element="step")
plt.axvline(0, color="black", linestyle="--", linewidth=1)
plt.axvline( EFFECT_THRESHOLD, color="gray", linestyle=":", linewidth=1)
plt.axvline(-EFFECT_THRESHOLD, color="gray", linestyle=":", linewidth=1)
plt.title("Distribution of NMN × Age Interaction Coefficients")
plt.xlabel("Interaction coefficient (NMN effect on aging slope)")
plt.tight_layout()
plt.savefig(OUT / "plots" / "effect_size_distribution.png", dpi=150)
plt.show()

# 6b. Rescue-gene counts: raw vs effect-filtered vs high-confidence
counts_df = pd.DataFrame({
    "raw":          {t: len(rescue[t])      for t in TISSUES},
    "effect_filt":  {t: len(rescue_filt[t]) for t in TISSUES},
    "high_conf":    {t: len(high_conf[t])   for t in TISSUES},
})
ax = counts_df.plot(kind="bar", figsize=(9, 5))
ax.set_title("Rescue genes by stringency tier")
ax.set_ylabel("number of genes")
ax.set_xlabel("")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(OUT / "plots" / "stringency_tiers.png", dpi=150)
plt.show()

# 6c. Cross-tissue robustness bar
if len(gene_counts):
    rob_tab = gene_counts["tissue_count"].value_counts().sort_index()
    plt.figure(figsize=(6, 4))
    rob_tab.plot(kind="bar", color="seagreen")
    plt.title("Cross-tissue robustness of rescue genes")
    plt.xlabel("# tissues a gene is rescued in")
    plt.ylabel("# genes")
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.savefig(OUT / "plots" / "robustness_counts.png", dpi=150)
    plt.show()

# 6d. Mitochondrial overlap bar
mito_count_df = pd.Series({t: len(mito_hits[t]) for t in TISSUES})
plt.figure(figsize=(6, 4))
mito_count_df.plot(kind="bar", color="indianred")
plt.title(f"Mitochondrial rescue genes per tissue\n(source: {mito_source})")
plt.ylabel("# mito genes in rescue list")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(OUT / "plots" / "mito_overlap.png", dpi=150)
plt.show()

# ============================================================
# 7. DETAILED DOWNSTREAM SUMMARY REPORT
# ============================================================
SUMMARY_PATH = OUT / "DOWNSTREAM_SUMMARY_REPORT.txt"

def hr(c="=", n=78):
    return c * n

def fmt_table(df, cols, n=25):
    if df is None or df.empty:
        return "      (none)"
    sub = df[cols].head(n).copy()
    def cell(v, c):
        if isinstance(v, (bool, np.bool_)):
            return "yes" if v else "no"
        if isinstance(v, (int, np.integer)):
            return str(int(v))
        if isinstance(v, (float, np.floating)):
            if np.isnan(v):
                return "NA"
            return f"{v:.3e}" if ("p" in c.lower() or "fdr" in c.lower()) \
                   else f"{v:+.3f}"
        return str(v)
    widths = {c: max(len(c), *(len(cell(v, c)) for v in sub[c])) for c in cols}
    out = ["  ".join(c.ljust(widths[c]) for c in cols),
           "  ".join("-" * widths[c] for c in cols)]
    for _, row in sub.iterrows():
        out.append("  ".join(cell(row[c], c).ljust(widths[c]) for c in cols))
    return "\n".join(out)

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
S = []
S.append(hr("#"))
S.append("#  GSE85718 — STAGE 2 DOWNSTREAM ANALYSIS : DETAILED SUMMARY REPORT")
S.append(hr("#"))
S.append(f"Generated   : {now}")
S.append(f"Input dir   : {os.path.abspath(str(GENELISTS))}")
S.append(f"Output dir  : {os.path.abspath(str(OUT))}")
S.append("")
S.append("Thresholds used:")
S.append(f"  |coef_interaction| >= {EFFECT_THRESHOLD}   (effect-size filter)")
S.append(f"  p_interaction      <  {P_THRESHOLD}   (high-confidence)")
S.append(f"  robustness         >= {MIN_TISSUES} tissues")
S.append(f"  MitoCarta source   :  {mito_source}")
S.append("")

# 1. Input sizes
S.append(hr())
S.append("1. INPUT RESCUE-GENE LISTS")
S.append(hr())
for t in TISSUES:
    S.append(f"  {t:16s}: {len(rescue[t])} genes")
S.append("")

# 2. Stringency tiers
S.append(hr())
S.append("2. STRINGENCY TIERS (raw -> effect-filtered -> high-confidence)")
S.append(hr())
S.append(counts_df.to_string())
S.append("")

# 3. High-confidence genes per tissue
S.append(hr())
S.append("3. HIGH-CONFIDENCE CANDIDATES (p_int < "
         f"{P_THRESHOLD} & |coef_int| >= {EFFECT_THRESHOLD})")
S.append(hr())
for t in TISSUES:
    S.append(f"  --- {t} (n={len(high_conf[t])}) ---")
    S.append(textwrap.indent(
        fmt_table(high_conf[t],
            ["gene", "coef_age_Control", "coef_interaction",
             "p_interaction", "fdr_interaction"], 25),
        "    "))
    S.append("")

# 4. Cross-tissue robustness
S.append(hr())
S.append("4. CROSS-TISSUE ROBUSTNESS")
S.append(hr())
S.append(f"Genes rescued in >= {MIN_TISSUES} tissues: {len(robust_genes)}")
S.append(f"Genes rescued in ALL 3 tissues          : {len(genes_all3)}")
if genes_all3:
    S.append("  " + ", ".join(genes_all3))
S.append("")
if len(robust_detail):
    S.append("Robust-gene detail (direction consistency across tissues):")
    S.append(textwrap.indent(
        fmt_table(robust_detail,
            ["gene", "n_tissues", "tissues", "mean_coef_interaction",
             "mean_coef_age_Control", "direction_consistent"], 50),
        "  "))
S.append("")

# 5. Mitochondrial enrichment
S.append(hr())
S.append("5. MITOCHONDRIAL PATHWAY OVERLAP")
S.append(hr())
S.append(f"MitoCarta reference source: {mito_source} "
         f"({len(mito_set)} symbols)")
S.append("")
me = pd.DataFrame(mito_enrich_res).T[["n_genes", "k_mito", "hyper_p"]]
me.columns = ["rescue_genes", "mito_hits", "hypergeom_p"]
S.append(me.to_string())
S.append("")
for t in TISSUES:
    if mito_hits[t]:
        S.append(f"  {t} mito genes: " + ", ".join(sorted(mito_hits[t])))
S.append("")

# 6. GSEA highlights
S.append(hr())
S.append("6. GSEA ON INTERACTION RANKING (per tissue)")
S.append(hr())
for t in TISSUES:
    tg = top_gsea_terms(gsea_top.get(t), n=10)
    S.append(f"  --- {t} ---")
    if tg is None:
        S.append("    (GSEA unavailable / skipped)")
        S.append("")
        continue
    up, down = tg
    S.append("    Positive NES (NMN raises old-age expression vs Control):")
    S.append(textwrap.indent(
        fmt_table(up, ["Term", "NES", "pval", "FDR"], 10), "      "))
    S.append("")
    S.append("    Negative NES (NMN lowers old-age expression vs Control):")
    S.append(textwrap.indent(
        fmt_table(down, ["Term", "NES", "pval", "FDR"], 10), "      "))
    S.append("")

# 7. Validation shortlist (intersection of high-confidence + robust + mito-aware)
S.append(hr())
S.append("7. SUGGESTED VALIDATION SHORTLIST")
S.append(hr())
S.append(textwrap.fill(
    "Prioritized as: high-confidence in any tissue, ranked by whether the gene "
    "is also cross-tissue robust and/or mitochondrial. These are the strongest "
    "candidates for qPCR / Western confirmation.", width=78))
S.append("")
hc_union = pd.concat([high_conf[t] for t in TISSUES if len(high_conf[t])],
                     ignore_index=True) if any(len(high_conf[t]) for t in TISSUES) \
           else pd.DataFrame(columns=all_genes.columns)
if len(hc_union):
    sl = (hc_union.groupby("gene")
          .agg(n_tissues=("tissue", "nunique"),
               best_p=("p_interaction", "min"),
               mean_coef_int=("coef_interaction", "mean"))
          .reset_index())
    sl["robust"]  = sl["gene"].isin(robust_genes)
    sl["mito"]    = sl["gene"].isin(mito_set)
    sl["priority"] = (sl["n_tissues"] * 2
                      + sl["robust"].astype(int) * 2
                      + sl["mito"].astype(int))
    sl = sl.sort_values(["priority", "best_p"],
                        ascending=[False, True]).reset_index(drop=True)
    sl.to_csv(OUT / "tables" / "Validation_Shortlist.tsv", sep="\t", index=False)
    S.append(textwrap.indent(
        fmt_table(sl,
            ["gene", "n_tissues", "best_p", "mean_coef_int",
             "robust", "mito", "priority"], 40),
        "  "))
else:
    S.append("  (no high-confidence genes at current thresholds — "
             "consider relaxing P_THRESHOLD or EFFECT_THRESHOLD)")
S.append("")

# 8. Interpretation notes
S.append(hr())
S.append("8. NOTES & CAVEATS")
S.append(hr())
S.append(textwrap.fill(
    "- Effect-size and p-value thresholds are tunable at the top of the script; "
    "with n=4/cell the interaction test is underpowered, so treat marginal hits "
    "as hypothesis-generating.", width=78))
S.append(textwrap.fill(
    f"- Mitochondrial enrichment used '{mito_source}'. If this is the fallback "
    "curated core, install the full MitoCarta3.0 mouse symbol list for a "
    "definitive test.", width=78))
S.append(textwrap.fill(
    "- GSEA Hallmark sets are human; mouse symbols were upper-cased as an "
    "ortholog proxy. KEGG_2019_Mouse and GO_BP_2021 are the mouse-appropriate "
    "references.", width=78))
S.append(textwrap.fill(
    "- The validation priority score weights cross-tissue robustness and "
    "mitochondrial membership, reflecting the study's muscle-mitochondria "
    "emphasis; adjust the weighting to suit your hypothesis.", width=78))
S.append("")

# 9. File manifest
S.append(hr())
S.append("9. OUTPUT FILE MANIFEST (results/downstream)")
S.append(hr())
for f in sorted(glob.glob(str(OUT / "**" / "*"), recursive=True)):
    if os.path.isfile(f):
        size = os.path.getsize(f)
        sz = (f"{size/1e6:.2f} MB" if size > 1e6 else
              f"{size/1e3:.1f} KB" if size > 1e3 else f"{size} B")
        S.append(f"  {f:60s} {sz:>10s}")
S.append("")

# 10. Run log
S.append(hr())
S.append("10. RUN LOG")
S.append(hr())
S.extend("  " + ln for ln in RUN_LOG)
S.append("")
S.append(hr("#"))
S.append("#  END OF DOWNSTREAM REPORT")
S.append(hr("#"))

with open(SUMMARY_PATH, "w") as fh:
    fh.write("\n".join(S) + "\n")

print("\n>>> Downstream summary written to:", os.path.abspath(str(SUMMARY_PATH)))
print(">>> Preview (first 50 lines):\n")
print("\n".join(S[:50]))

# ============================================================
# Final banner
# ============================================================
print("\n" + "=" * 60)
print("DONE — Stage 2 downstream analysis")
print("=" * 60)
print(textwrap.dedent(f"""
  Outputs under: {os.path.abspath(str(OUT))}
    DOWNSTREAM_SUMMARY_REPORT.txt          <-- detailed all-in-one report
    tables/EffectFiltered_<tissue>.tsv
    tables/High_Confidence_<tissue>.tsv
    tables/Cross_Tissue_Robust_Rescue_Genes.tsv
    tables/Robust_Gene_Summary.tsv
    tables/Validation_Shortlist.tsv
    GSEA/GSEA_downstream_<tissue>.tsv
    plots/effect_size_distribution.png
    plots/stringency_tiers.png
    plots/robustness_counts.png
    plots/mito_overlap.png
"""))
subprocess.run(f"find {OUT} -type f | sort", shell=True)

"""# Stage 3"""

# -*- coding: utf-8 -*-
"""
GSE85718 — STAGE 3: Deep-Dive on Cross-Tissue Robust NMN-Rescue Genes
=====================================================================
Consumes ONLY existing outputs from stage 1 & stage 2:
    results/downstream/tables/Cross_Tissue_Robust_Rescue_Genes.tsv
    results/downstream/tables/Robust_Gene_Summary.tsv          (optional)
    results/downstream/tables/High_Confidence_<tissue>.tsv     (optional)
    results/downstream/tables/Validation_Shortlist.tsv         (optional)
    results/genelists/NMN_Rescue_Genes_<tissue>.tsv
    results/downstream/GSEA/<tissue>/gseapy.*prerank*report*.csv   (optional)
    results/downstream/GSEA/GSEA_downstream_<tissue>.tsv           (optional)

Performs (no new data, no experiments):
  1. Master annotation table for the robust genes
  2. Robust vs high-confidence breakdown
  3. Direction-consistency + effect-size variability across tissues
  4. Overlap with mitochondrial hits (reuses stage-2 mito logic/files)
  5. GSEA leading-edge overlap (which robust genes drove enriched pathways)
  6. Prioritized final summary table
  7. Visualizations
  8. ROBUST_GENES_SUMMARY_REPORT.txt   (detailed all-in-one)
"""

# ============================================================
# 0. Setup
# ============================================================
import os, glob, re, textwrap, datetime, warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
try:
    import seaborn as sns
    HAVE_SNS = True
except Exception:
    HAVE_SNS = False
warnings.filterwarnings("ignore")

WORK = "/content/GSE85718"
if os.path.isdir(WORK):
    os.chdir(WORK)

RESULTS   = Path("results")
GENELISTS = RESULTS / "genelists"
DOWN      = RESULTS / "downstream"
DOWN_TAB  = DOWN / "tables"
GSEA_DIR  = DOWN / "GSEA"
OUT       = DOWN / "robust"               # stage-3 outputs live here
for d in [OUT, OUT / "tables", OUT / "plots"]:
    d.mkdir(parents=True, exist_ok=True)

TISSUES = ["Skeletal_muscle", "Liver", "WAT"]

RUN_LOG = []
def log(msg):
    print(msg)
    RUN_LOG.append(str(msg))

def norm_gene(s):
    return pd.Series(s, dtype="object").astype(str).str.upper().str.strip()

log(">>> STAGE 3 robust-gene deep dive")
log(">>> Working dir: " + os.path.abspath("."))

# ============================================================
# 1. Master annotation table
# ============================================================
ROBUST_F = DOWN_TAB / "Cross_Tissue_Robust_Rescue_Genes.tsv"
if not ROBUST_F.exists():
    raise SystemExit(f"Missing {ROBUST_F} — run stage 2 first.")

robust_long = pd.read_csv(ROBUST_F, sep="\t")
robust_long["gene"] = norm_gene(robust_long["gene"])
robust_genes = sorted(robust_long["gene"].unique())
log(f">>> Robust genes loaded: {len(robust_genes)}")

# --- pull per-tissue coefficients straight from the rescue lists ---
def load_rescue(tissue):
    f = GENELISTS / f"NMN_Rescue_Genes_{tissue}.tsv"
    if not f.exists():
        log(f"!!! MISSING rescue list: {f}")
        return pd.DataFrame()
    d = pd.read_csv(f, sep="\t")
    d["gene"] = norm_gene(d["gene"])
    return d

rescue = {t: load_rescue(t) for t in TISSUES}

# Build a wide table: one row per robust gene, coef/p per tissue
master = pd.DataFrame({"gene": robust_genes})
for t in TISSUES:
    d = rescue[t]
    if d.empty:
        master[f"coef_int_{t}"] = np.nan
        master[f"p_int_{t}"]    = np.nan
        master[f"in_{t}"]       = False
        continue
    sub = (d[["gene"]].assign(present=True)
           .merge(d.rename(columns={
               "coef_interaction": f"coef_int_{t}",
               "p_interaction":    f"p_int_{t}"})
               [["gene", f"coef_int_{t}", f"p_int_{t}"]],
               on="gene", how="left")
           .drop_duplicates("gene"))
    master = master.merge(
        sub.rename(columns={"present": f"in_{t}"}), on="gene", how="left")
    master[f"in_{t}"] = master[f"in_{t}"].fillna(False)

coef_cols = [f"coef_int_{t}" for t in TISSUES]
p_cols    = [f"p_int_{t}"    for t in TISSUES]

# n_tissues actually carrying the gene (recomputed for safety)
master["n_tissues"] = master[[f"in_{t}" for t in TISSUES]].sum(axis=1).astype(int)
master["tissues"]   = master.apply(
    lambda r: ", ".join(t for t in TISSUES if r[f"in_{t}"]), axis=1)

# --- high-confidence flag (union across tissues) ---
hc_union = []
for t in TISSUES:
    f = DOWN_TAB / f"High_Confidence_{t}.tsv"
    if f.exists():
        h = pd.read_csv(f, sep="\t")
        h["gene"] = norm_gene(h["gene"])
        h["hc_tissue"] = t
        hc_union.append(h[["gene", "hc_tissue"]])
hc_union = (pd.concat(hc_union, ignore_index=True)
            if hc_union else pd.DataFrame(columns=["gene", "hc_tissue"]))
hc_genes = set(hc_union["gene"])
master["is_high_confidence"] = master["gene"].isin(hc_genes)
master["hc_tissues"] = master["gene"].map(
    hc_union.groupby("gene")["hc_tissue"]
    .apply(lambda s: ", ".join(sorted(set(s)))).to_dict()).fillna("")

master.to_csv(OUT / "tables" / "Robust_Genes_Master_Annotation.tsv",
              sep="\t", index=False)
log(f">>> Master annotation written ({master.shape[0]} genes x "
    f"{master.shape[1]} cols)")

# ============================================================
# 2. Robust vs high-confidence breakdown
# ============================================================
n_robust = len(master)
n_hc     = int(master["is_high_confidence"].sum())
log(f"\n>>> Robust genes total          : {n_robust}")
log(f">>> Robust AND high-confidence  : {n_hc}")
log(f">>> Robust only (not HC)        : {n_robust - n_hc}")

# ============================================================
# 3. Direction consistency + effect-size variability
# ============================================================
def sign_consistency(row):
    vals = [row[c] for c in coef_cols if pd.notna(row[c])]
    if len(vals) < 2:
        return np.nan
    signs = {np.sign(v) for v in vals if v != 0}
    return len(signs) == 1

master["mean_coef_interaction"] = master[coef_cols].mean(axis=1)
master["coef_std"]              = master[coef_cols].std(axis=1)
master["coef_min"]             = master[coef_cols].min(axis=1)
master["coef_max"]             = master[coef_cols].max(axis=1)
master["coef_range"]           = master["coef_max"] - master["coef_min"]
master["direction_consistent"] = master.apply(sign_consistency, axis=1)
master["best_p"]               = master[p_cols].min(axis=1)

# Coefficient of variation as a stability metric (guard against /0)
master["coef_cv"] = (master["coef_std"] /
                     master["mean_coef_interaction"].abs().replace(0, np.nan))

# If stage-2 already produced a robust summary, reconcile direction flag
RS_F = DOWN_TAB / "Robust_Gene_Summary.tsv"
if RS_F.exists():
    rs = pd.read_csv(RS_F, sep="\t")
    rs["gene"] = norm_gene(rs["gene"])
    if "direction_consistent" in rs.columns:
        prior = rs.set_index("gene")["direction_consistent"].to_dict()
        master["direction_consistent_stage2"] = master["gene"].map(prior)

master.to_csv(OUT / "tables" / "Robust_Genes_with_Effect_Sizes.tsv",
              sep="\t", index=False)

n_consistent = int((master["direction_consistent"] == True).sum())
n_discordant = int((master["direction_consistent"] == False).sum())
log(f"\n>>> Direction consistent across tissues : {n_consistent}")
log(f">>> Direction DISCORDANT (sign flips)   : {n_discordant}")

# ============================================================
# 4. Overlap with mitochondrial hits
#    Reuse stage-2 logic: local MitoCarta -> Validation_Shortlist
#    mito flag -> curated fallback core set.
# ============================================================
FALLBACK_MITO = {
    "NDUFA1","NDUFA2","NDUFA9","NDUFB8","NDUFS1","NDUFS3","NDUFV1","SDHA","SDHB",
    "UQCRC1","UQCRC2","CYC1","COX4I1","COX5A","COX5B","COX6A1","COX7A1","COX8B",
    "ATP5A1","ATP5B","ATP5C1","ATP5O","ATP5J","CS","IDH3A","SUCLA2","FH1","MDH2",
    "ACO2","OGDH","PDHA1","PDHB","DLAT","CPT1B","CPT2","ACADM","ACADL","ACADVL",
    "HADHA","HADHB","ECI1","SLC25A4","SLC25A20","TFAM","NRF1","PPARGC1A","ESRRA",
    "MFN1","MFN2","OPA1","DNM1L","PINK1","PRKN","SOD2","TFB1M","TFB2M","POLG",
    "MRPL12","MRPS12","TIMM23","TOMM20","VDAC1","VDAC2","CYCS","UCP2","UCP3",
}

def load_mito_set():
    for cand in ["MitoCarta3.0_Mouse_Symbols.txt",
                 str(GENELISTS / "MitoCarta3.0_Mouse_Symbols.txt")]:
        if os.path.exists(cand):
            try:
                s = set(norm_gene(pd.read_csv(cand, header=None)[0]))
                return s, f"local:{cand}"
            except Exception as e:
                log(f">>> MitoCarta local read failed: {e}")
    # reuse stage-2 mito calls recorded in the validation shortlist
    vf = DOWN_TAB / "Validation_Shortlist.tsv"
    if vf.exists():
        try:
            v = pd.read_csv(vf, sep="\t")
            if "mito" in v.columns:
                v["gene"] = norm_gene(v["gene"])
                s = set(v.loc[v["mito"] == True, "gene"])
                if s:
                    return s, "stage2:Validation_Shortlist.mito"
        except Exception as e:
            log(f">>> Shortlist mito read failed: {e}")
    return set(FALLBACK_MITO), "fallback:curated_core"

mito_set, mito_source = load_mito_set()
master["is_mitochondrial"] = master["gene"].isin(mito_set)
mito_robust = master.loc[master["is_mitochondrial"], "gene"].tolist()
log(f"\n>>> Mito reference source: {mito_source} ({len(mito_set)} symbols)")
log(f">>> Robust genes that are mitochondrial: {len(mito_robust)} "
    + ("[" + ", ".join(mito_robust) + "]" if mito_robust else ""))

# Hypergeometric: are mito genes over-represented among the robust set?
try:
    from scipy.stats import hypergeom
    UNIVERSE = 20000
    k = len(mito_robust); n_list = n_robust; n_mito = len(mito_set)
    mito_hyper_p = hypergeom.sf(k - 1, UNIVERSE, n_mito, n_list)
except Exception:
    mito_hyper_p = np.nan
log(f">>> Mito hypergeometric p among robust set: {mito_hyper_p:.3e}")

# ============================================================
# 5. GSEA leading-edge overlap
#    Parse existing GSEA reports; pull lead genes; intersect robust set.
# ============================================================
def find_gsea_report(tissue):
    cands = []
    cands += glob.glob(str(GSEA_DIR / tissue / "*prerank*report*.csv"))
    cands += glob.glob(str(GSEA_DIR / tissue / "*report*.csv"))
    cands += [str(GSEA_DIR / f"GSEA_downstream_{tissue}.tsv")]
    for c in cands:
        if os.path.exists(c):
            return c
    return None

def read_gsea(path):
    sep = "\t" if path.endswith(".tsv") else ","
    try:
        df = pd.read_csv(path, sep=sep)
    except Exception:
        return pd.DataFrame()
    # normalise the columns we care about
    ren = {}
    for c in df.columns:
        lc = c.lower().replace(" ", "").replace("-", "").replace("_", "")
        if lc == "term": ren[c] = "Term"
        elif lc == "nes": ren[c] = "NES"
        elif lc in ("fdrqval", "fdr"): ren[c] = "FDR"
        elif lc in ("nompval", "pval", "pvalue"): ren[c] = "pval"
        elif lc in ("leadgenes", "leadingedge", "ledgenes",
                    "leadinggenes", "genes"): ren[c] = "Lead_genes"
    return df.rename(columns=ren)

ROBUST_SET = set(robust_genes)
lead_overlap_rows = []
gsea_term_hits    = {}
for t in TISSUES:
    p = find_gsea_report(t)
    if p is None:
        log(f">>> GSEA report for {t}: not found — skipped.")
        gsea_term_hits[t] = pd.DataFrame()
        continue
    g = read_gsea(p)
    if g.empty or "Lead_genes" not in g.columns:
        log(f">>> GSEA report for {t}: no lead-gene column — skipped.")
        gsea_term_hits[t] = pd.DataFrame()
        continue
    rows = []
    for _, r in g.iterrows():
        lead = str(r.get("Lead_genes", ""))
        lead_set = {x for x in re.split(r"[;,/\s]+", lead.upper()) if x}
        hit = sorted(lead_set & ROBUST_SET)
        if hit:
            rows.append({
                "tissue": t,
                "Term": r.get("Term", ""),
                "NES": pd.to_numeric(r.get("NES", np.nan), errors="coerce"),
                "FDR": pd.to_numeric(r.get("FDR", np.nan), errors="coerce"),
                "n_robust_in_lead": len(hit),
                "robust_lead_genes": ", ".join(hit),
            })
            for gn in hit:
                lead_overlap_rows.append({"gene": gn, "tissue": t,
                                          "Term": r.get("Term", "")})
    th = pd.DataFrame(rows)
    if len(th):
        th = th.sort_values("n_robust_in_lead", ascending=False)
        th.to_csv(OUT / "tables" / f"GSEA_LeadingEdge_RobustHits_{t}.tsv",
                  sep="\t", index=False)
    gsea_term_hits[t] = th
    log(f">>> GSEA leading-edge robust hits {t}: "
        f"{len(th)} terms contain >=1 robust gene")

lead_long = pd.DataFrame(lead_overlap_rows)
if len(lead_long):
    lead_per_gene = (lead_long.groupby("gene")
                     .agg(n_terms=("Term", "nunique"),
                          tissues=("tissue", lambda s: ", ".join(sorted(set(s)))))
                     .reset_index().sort_values("n_terms", ascending=False))
    lead_per_gene.to_csv(OUT / "tables" / "Robust_Genes_GSEA_LeadDriver.tsv",
                         sep="\t", index=False)
    master["gsea_lead_terms"] = master["gene"].map(
        lead_per_gene.set_index("gene")["n_terms"].to_dict()).fillna(0).astype(int)
else:
    master["gsea_lead_terms"] = 0
    log(">>> No GSEA leading-edge overlap available.")

# ============================================================
# 6. Prioritized final summary table
# ============================================================
final = master[[
    "gene", "n_tissues", "tissues", "direction_consistent",
    "is_high_confidence", "is_mitochondrial",
    "mean_coef_interaction", "coef_std", "coef_range",
    "best_p", "gsea_lead_terms"
]].copy()

# composite priority: breadth + confidence + mito + pathway-driver + consistency
final["priority"] = (
    final["n_tissues"] * 2
    + final["is_high_confidence"].astype(int) * 2
    + final["is_mitochondrial"].astype(int) * 1
    + (final["gsea_lead_terms"] > 0).astype(int) * 1
    + (final["direction_consistent"] == True).astype(int) * 1
)
final = final.sort_values(
    ["priority", "n_tissues", "is_high_confidence", "best_p"],
    ascending=[False, False, False, True]).reset_index(drop=True)
final.to_csv(OUT / "tables" / "Robust_Genes_Final_Summary.tsv",
             sep="\t", index=False)
log("\n>>> Final prioritized summary (top 10):")
for _, r in final.head(10).iterrows():
    log(f"   {r['gene']:12s} prio={int(r['priority'])} "
        f"n_tis={int(r['n_tissues'])} HC={r['is_high_confidence']} "
        f"mito={r['is_mitochondrial']} lead={int(r['gsea_lead_terms'])}")

# ============================================================
# 7. Visualizations
# ============================================================
# 7a. Heatmap of per-tissue interaction coefficients
hm = master.set_index("gene")[coef_cols].copy()
hm.columns = [c.replace("coef_int_", "") for c in hm.columns]
hm = hm.loc[final["gene"]]                      # order by priority
plt.figure(figsize=(7, max(5, 0.28 * len(hm))))
if HAVE_SNS:
    sns.heatmap(hm, cmap="vlag", center=0,
                cbar_kws={"label": "coef_interaction"},
                linewidths=0.3, linecolor="white")
else:
    plt.imshow(hm.values, cmap="bwr", aspect="auto",
               vmin=-np.nanmax(np.abs(hm.values)),
               vmax=np.nanmax(np.abs(hm.values)))
    plt.yticks(range(len(hm)), hm.index, fontsize=6)
    plt.xticks(range(hm.shape[1]), hm.columns)
    plt.colorbar(label="coef_interaction")
plt.title("Robust genes: NMN×Age interaction coefficient by tissue")
plt.tight_layout()
plt.savefig(OUT / "plots" / "robust_coef_heatmap.png", dpi=150)
plt.show()

# 7b. Effect-size variability (mean vs std), coloured by category
plt.figure(figsize=(7, 6))
colors = np.where(master["is_mitochondrial"], "indianred",
          np.where(master["is_high_confidence"], "steelblue", "gray"))
plt.scatter(master["mean_coef_interaction"], master["coef_std"],
            c=colors, s=40, edgecolor="k", linewidth=0.3)
for _, r in master.iterrows():
    if r["is_mitochondrial"] or r["is_high_confidence"]:
        plt.annotate(r["gene"],
                     (r["mean_coef_interaction"], r["coef_std"]),
                     fontsize=6, alpha=0.8)
plt.axvline(0, color="black", linestyle="--", linewidth=0.8)
plt.xlabel("mean interaction coefficient (across tissues)")
plt.ylabel("std of interaction coefficient (cross-tissue spread)")
plt.title("Robust genes: effect-size strength vs cross-tissue variability\n"
          "(red=mito, blue=high-conf, gray=other)")
plt.tight_layout()
plt.savefig(OUT / "plots" / "robust_effect_variability.png", dpi=150)
plt.show()

# 7c. Category breakdown bar
cat = pd.Series({
    "robust total":         n_robust,
    "high-confidence":      n_hc,
    "mitochondrial":        len(mito_robust),
    "dir. consistent":      n_consistent,
    "GSEA lead-driver":     int((master["gsea_lead_terms"] > 0).sum()),
})
plt.figure(figsize=(7, 4))
cat.plot(kind="bar", color="slateblue")
plt.title("Robust-gene categories")
plt.ylabel("# genes")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.savefig(OUT / "plots" / "robust_category_breakdown.png", dpi=150)
plt.show()

# ============================================================
# 8. DETAILED SUMMARY REPORT
# ============================================================
SUMMARY_PATH = OUT / "ROBUST_GENES_SUMMARY_REPORT.txt"

def hr(c="=", n=78):
    return c * n

def fmt_table(df, cols, n=50):
    if df is None or len(df) == 0:
        return "      (none)"
    cols = [c for c in cols if c in df.columns]
    sub = df[cols].head(n).copy()
    def cell(v, c):
        if isinstance(v, (bool, np.bool_)):
            return "yes" if v else "no"
        if v is None or (isinstance(v, float) and np.isnan(v)):
            return "NA"
        if isinstance(v, (int, np.integer)):
            return str(int(v))
        if isinstance(v, (float, np.floating)):
            return (f"{v:.2e}" if ("p" in c.lower() or "fdr" in c.lower())
                    else f"{v:+.3f}")
        return str(v)
    widths = {c: max(len(c), *(len(cell(v, c)) for v in sub[c])) for c in cols}
    out = ["  ".join(c.ljust(widths[c]) for c in cols),
           "  ".join("-" * widths[c] for c in cols)]
    for _, row in sub.iterrows():
        out.append("  ".join(cell(row[c], c).ljust(widths[c]) for c in cols))
    return "\n".join(out)

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
S = []
S.append(hr("#"))
S.append("#  GSE85718 — STAGE 3 : CROSS-TISSUE ROBUST GENE DEEP-DIVE REPORT")
S.append(hr("#"))
S.append(f"Generated  : {now}")
S.append(f"Input dir  : {os.path.abspath(str(DOWN_TAB))}")
S.append(f"Output dir : {os.path.abspath(str(OUT))}")
S.append("")

# 1
S.append(hr())
S.append("1. OVERVIEW")
S.append(hr())
S.append(f"  Robust genes (rescued in >=2 tissues) : {n_robust}")
S.append(f"  ...also high-confidence               : {n_hc}")
S.append(f"  ...mitochondrial ({mito_source})      : {len(mito_robust)}")
S.append(f"  ...direction-consistent across tissues: {n_consistent}")
S.append(f"  ...direction-DISCORDANT (sign flip)   : {n_discordant}")
S.append(f"  ...GSEA leading-edge drivers          : "
         f"{int((master['gsea_lead_terms'] > 0).sum())}")
S.append("")

# 2
S.append(hr())
S.append("2. MASTER ANNOTATION (per-tissue interaction coefficients)")
S.append(hr())
S.append(fmt_table(master,
    ["gene", "n_tissues", "tissues"] + coef_cols +
    ["is_high_confidence", "is_mitochondrial"], 50))
S.append("")

# 3
S.append(hr())
S.append("3. EFFECT-SIZE CONSISTENCY ACROSS TISSUES")
S.append(hr())
S.append("Lower coef_std / coef_range = more reproducible rescue magnitude.")
S.append("")
S.append(fmt_table(master.sort_values("coef_std"),
    ["gene", "mean_coef_interaction", "coef_std", "coef_range",
     "direction_consistent"], 50))
S.append("")
disc = master[master["direction_consistent"] == False]
S.append(f"Direction-DISCORDANT genes (NMN flips sign between tissues): "
         f"{len(disc)}")
if len(disc):
    S.append(fmt_table(disc, ["gene", "tissues"] + coef_cols, 50))
S.append("")

# 4
S.append(hr())
S.append("4. MITOCHONDRIAL OVERLAP")
S.append(hr())
S.append(f"  Reference source : {mito_source} ({len(mito_set)} symbols)")
S.append(f"  Robust & mito    : {len(mito_robust)}")
S.append(f"  Hypergeometric p : {mito_hyper_p:.3e} "
         "(over-representation among robust set)")
if mito_robust:
    S.append("  Genes: " + ", ".join(mito_robust))
S.append("")

# 5
S.append(hr())
S.append("5. GSEA LEADING-EDGE OVERLAP (robust genes that drove pathways)")
S.append(hr())
any_lead = False
for t in TISSUES:
    th = gsea_term_hits.get(t, pd.DataFrame())
    S.append(f"  --- {t} ---")
    if th is None or len(th) == 0:
        S.append("    (no GSEA leading-edge data)")
    else:
        any_lead = True
        S.append(textwrap.indent(
            fmt_table(th, ["Term", "NES", "FDR",
                           "n_robust_in_lead", "robust_lead_genes"], 12),
            "    "))
    S.append("")
if not any_lead:
    S.append("  No GSEA reports with lead-gene columns were found.")
    S.append("")

# 6
S.append(hr())
S.append("6. PRIORITIZED FINAL SUMMARY")
S.append(hr())
S.append(textwrap.fill(
    "Priority = 2*n_tissues + 2*high_confidence + 1*mitochondrial "
    "+ 1*GSEA_lead_driver + 1*direction_consistent. Higher = stronger "
    "evidence as a tissue-agnostic NMN-rescued aging gene.", width=78))
S.append("")
S.append(fmt_table(final,
    ["gene", "n_tissues", "direction_consistent", "is_high_confidence",
     "is_mitochondrial", "gsea_lead_terms", "mean_coef_interaction",
     "best_p", "priority"], 50))
S.append("")

# 7
S.append(hr())
S.append("7. NOTES & CAVEATS")
S.append(hr())
S.append(textwrap.fill(
    "- This stage adds NO new data; every metric is derived from stage-1/2 "
    "outputs, so conclusions inherit the n=4/cell power limits of the original "
    "interaction test.", width=78))
S.append(textwrap.fill(
    f"- Mitochondrial annotation used '{mito_source}'. If this is the curated "
    "fallback, install the full MitoCarta3.0 mouse list and re-run for a "
    "definitive enrichment p-value.", width=78))
S.append(textwrap.fill(
    "- Direction discordance means NMN moves the gene oppositely in different "
    "tissues; such genes are robust in 'frequency' but not in 'mechanism' and "
    "should be interpreted tissue-by-tissue.", width=78))
S.append(textwrap.fill(
    "- GSEA leading-edge overlap depends on stage-2 having saved per-tissue "
    "report CSVs with a lead-gene column; if absent, that section is empty but "
    "the rest of the report is unaffected.", width=78))
S.append("")

# 8 manifest + log
S.append(hr())
S.append("8. OUTPUT FILE MANIFEST (results/downstream/robust)")
S.append(hr())
for f in sorted(glob.glob(str(OUT / "**" / "*"), recursive=True)):
    if os.path.isfile(f):
        size = os.path.getsize(f)
        sz = (f"{size/1e6:.2f} MB" if size > 1e6 else
              f"{size/1e3:.1f} KB" if size > 1e3 else f"{size} B")
        S.append(f"  {f:62s} {sz:>10s}")
S.append("")
S.append(hr())
S.append("9. RUN LOG")
S.append(hr())
S.extend("  " + ln for ln in RUN_LOG)
S.append("")
S.append(hr("#"))
S.append("#  END OF ROBUST-GENE REPORT")
S.append(hr("#"))

with open(SUMMARY_PATH, "w") as fh:
    fh.write("\n".join(S) + "\n")

print("\n>>> Robust-gene report written to:",
      os.path.abspath(str(SUMMARY_PATH)))
print(">>> Preview (first 45 lines):\n")
print("\n".join(S[:45]))

# ============================================================
# Final banner
# ============================================================
print("\n" + "=" * 60)
print("DONE — Stage 3 robust-gene deep dive")
print("=" * 60)
print(textwrap.dedent(f"""
  Outputs under: {os.path.abspath(str(OUT))}
    ROBUST_GENES_SUMMARY_REPORT.txt            <-- detailed all-in-one
    tables/Robust_Genes_Master_Annotation.tsv
    tables/Robust_Genes_with_Effect_Sizes.tsv
    tables/Robust_Genes_Final_Summary.tsv
    tables/Robust_Genes_GSEA_LeadDriver.tsv
    tables/GSEA_LeadingEdge_RobustHits_<tissue>.tsv
    plots/robust_coef_heatmap.png
    plots/robust_effect_variability.png
    plots/robust_category_breakdown.png
"""))

"""# Stage 4"""

# -*- coding: utf-8 -*-
"""
GSE85718 — Build standardized GOBP + KEGG GMT files from pipeline outputs ONLY.
No GEO re-download, no re-fit of the age*treatment model.
Uses the SAME Enrichr libraries the pipeline already used:
    GOBP : GO_Biological_Process_2021
    KEGG : KEGG_2019_Mouse
For each source gene list it writes, per collection:
    *_associated_fullset.gmt  -> standard library members of every hit term (GSEA-ready)
    *_associated_overlap.gmt  -> only the pipeline genes that fall in each term (audit)
plus a per-source association TSV and a global build index.
"""
# %pip -q install gseapy

import os, re
from pathlib import Path
import pandas as pd
import gseapy as gp

# ------------------------------------------------------------------
# Paths (same workspace as the pipeline)
# ------------------------------------------------------------------
WORK       = Path("/content/GSE85718")
GENELISTS  = WORK / "results" / "genelists"
DOWN_TAB   = WORK / "results" / "downstream" / "tables"
ROBUST_TAB = WORK / "results" / "downstream" / "robust" / "tables"
OUT        = WORK / "results" / "pathways"
OUT_GMT    = OUT / "gmt"
OUT_TAB    = OUT / "tables"
for d in (OUT, OUT_GMT, OUT_TAB):
    d.mkdir(parents=True, exist_ok=True)

TISSUES = ["Skeletal_muscle", "Liver", "WAT"]
LIBS = {
    "GOBP": "GO_Biological_Process_2021",
    "KEGG": "KEGG_2019_Mouse",
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
_BAD = {"", "NAN", "NA", "NONE", "---"}

def norm_genes(xs):
    return sorted({str(x).upper().strip() for x in xs
                   if str(x).upper().strip() not in _BAD})

def load_txt_list(path):
    return norm_genes(Path(path).read_text().splitlines()) if path.exists() else []

def load_query_sets():
    """Every query list is built ONLY from stage-1/2/3 outputs."""
    qs = {}
    for t in TISSUES:
        # primary: the artifact-filtered clean .txt export
        g = load_txt_list(GENELISTS / f"GeneList_NMN_Rescue_{t}.txt")
        # fallback: the full TSV (re-apply the artifact filter)
        if not g:
            f = GENELISTS / f"NMN_Rescue_Genes_{t}.tsv"
            if f.exists():
                d = pd.read_csv(f, sep="\t")
                if "artifact_flag" in d.columns:
                    d = d[d["artifact_flag"].fillna("").astype(str).str.strip().eq("")]
                g = norm_genes(d["gene"])
        if g:
            qs[t] = g

    # robust set (rescued in >= 2 tissues) — first table that exists wins
    for cand in [ROBUST_TAB / "Robust_Genes_Final_Summary.tsv",
                 DOWN_TAB   / "Cross_Tissue_Robust_Rescue_Genes.tsv",
                 DOWN_TAB   / "Robust_Gene_Summary.tsv"]:
        if cand.exists():
            d = pd.read_csv(cand, sep="\t")
            if "gene" in d.columns:
                qs["Robust"] = norm_genes(d["gene"])
                break

    # union of the three tissue lists
    union = norm_genes(g for t in TISSUES for g in qs.get(t, []))
    if union:
        qs["Union_rescue"] = union

    return {k: v for k, v in qs.items() if v}

def parse_term_id(term, collection):
    if collection == "GOBP":
        m = re.search(r"(GO:\d{7})", str(term));                 return m.group(1) if m else ""
    if collection == "KEGG":
        m = re.search(r"(mmu\d{5}|map\d{5})", str(term), re.I);   return m.group(1) if m else ""
    return ""

def write_gmt(path, rows):
    """rows: iterable of (term, description, gene_list)."""
    n = 0
    with open(path, "w") as fh:
        for term, desc, genes in rows:
            genes = norm_genes(genes)
            if not genes:
                continue
            fh.write("\t".join([str(term), str(desc)] + genes) + "\n")
            n += 1
    return n

def associate(query, lib_dict, collection):
    qset = set(query)
    recs = []
    for term, members in lib_dict.items():
        mem = norm_genes(members)
        hit = sorted(qset & set(mem))
        if hit:
            recs.append(dict(collection=collection, term=term,
                             term_id=parse_term_id(term, collection),
                             n_library=len(mem), n_overlap=len(hit),
                             overlap_genes=",".join(hit),
                             library_genes=mem, overlap_list=hit))
    recs.sort(key=lambda r: (-r["n_overlap"], r["term"]))
    return recs

def fetch_library(name):
    """These libs live on the MAIN Enrichr server -> organism='Human'.
    Fall back to the mouse endpoint only if that fails."""
    for org in ("Human", "Mouse"):
        try:
            lib = gp.get_library(name=name, organism=org)
            if lib:
                print(f"    fetched {name} via organism={org}: {len(lib)} terms")
                return lib
        except Exception as e:
            print(f"    organism={org} failed for {name}: {e}")
    raise RuntimeError(f"Could not fetch Enrichr library: {name}")

# ------------------------------------------------------------------
# 1. Fetch the two libraries once
# ------------------------------------------------------------------
libraries = {}
for tag, name in LIBS.items():
    print(f">>> fetching {name}")
    libraries[tag] = fetch_library(name)

# ------------------------------------------------------------------
# 2. Query gene sets from pipeline outputs
# ------------------------------------------------------------------
queries = load_query_sets()
if not queries:
    raise SystemExit("No pipeline gene lists found under results/genelists — run the pipeline first.")
for k, v in queries.items():
    print(f">>> query {k:16s} n={len(v)}")

# ------------------------------------------------------------------
# 3. Associate + write GMTs
# ------------------------------------------------------------------
index_rows = []
for source, genes in queries.items():
    for tag, lib in libraries.items():
        recs = associate(genes, lib, tag)

        pd.DataFrame([{k: r[k] for k in
                       ("collection", "term", "term_id",
                        "n_library", "n_overlap", "overlap_genes")}
                      for r in recs]).to_csv(
            OUT_TAB / f"{source}__{tag}_associations.tsv", sep="\t", index=False)

        n_full = write_gmt(OUT_GMT / f"{source}__{tag}_associated_fullset.gmt",
                           ((r["term"], r["term_id"] or r["term"], r["library_genes"])
                            for r in recs))
        n_ovl  = write_gmt(OUT_GMT / f"{source}__{tag}_associated_overlap.gmt",
                           ((r["term"], r["term_id"] or source, r["overlap_list"])
                            for r in recs))

        index_rows.append(dict(source=source, collection=tag,
                               n_query=len(genes), n_associated_terms=len(recs),
                               gmt_fullset=n_full, gmt_overlap=n_ovl))
        print(f"    {source:16s} {tag}: {len(recs)} associated terms "
              f"(fullset={n_full}, overlap={n_ovl})")

pd.DataFrame(index_rows).to_csv(OUT / "gmt_build_index.tsv", sep="\t", index=False)
print("\n>>> GMTs written to:", OUT_GMT)
print(">>> index:", OUT / "gmt_build_index.tsv")

"""## Restriction step"""

# -*- coding: utf-8 -*-
"""
GSE85718 — RESTRICT *ONLY* Robust x GOBP (run AFTER the GMT-build cell).
Uses in-memory `libraries`, `queries`, `associate()`, `write_gmt()`, `norm_genes()`.

Fix vs previous attempt: with n=15 Robust genes, min_overlap=2 left only 2 terms.
So here min_overlap=1 (keep singletons), then trim redundancy via:
    - library size cap (drop vague umbrella GO terms)
    - hypergeometric ranking (specificity)
    - Jaccard collapse on overlap-gene sets (parent/child + same-gene dedupe)
Target: ~20-30 terms.

Writes ONLY (separate, non-clobbering filenames):
    Robust__GOBP_RESTRICTED.tsv          -> audit table (with hyper_p)
    Robust__GOBP_RESTRICTED_fullset.gmt  -> GSEA-ready (standard library members)
    Robust__GOBP_RESTRICTED_overlap.gmt  -> audit (only Robust genes per term)
Leaves every other source/collection and the prior GMTs/index untouched.
"""
# %pip -q install scipy
from scipy.stats import hypergeom
import pandas as pd

# ------------------------------------------------------------------
# Knobs — tuned for a tiny (n~15) query. Adjust ONLY these to hit 20-30.
# ------------------------------------------------------------------
SOURCE       = "Robust"
TAG          = "GOBP"
UNIVERSE     = 20000     # background gene count for the hypergeometric test
MIN_OVERLAP  = 1         # KEEP singletons (raising to 2 collapsed to 2 terms)
MAX_LIB_SIZE = 500       # drop huge, vague GO terms
JACCARD_MAX  = 0.5       # collapse terms whose overlap-gene sets are >= this similar
TOP_N        = 30        # hard cap

# ------------------------------------------------------------------
def _hyper_p(k, n_lib, n_query, universe=UNIVERSE):
    """P(X >= k): overlap of an n_query-gene list with an n_lib-gene term."""
    return float(hypergeom.sf(k - 1, universe, n_lib, n_query))

def restrict(recs, n_query,
             min_overlap=MIN_OVERLAP, max_lib=MAX_LIB_SIZE,
             jaccard_max=JACCARD_MAX, top_n=TOP_N):
    # 1. size + overlap prefilter
    cand = [r for r in recs
            if r["n_overlap"] >= min_overlap and r["n_library"] <= max_lib]
    # 2. hypergeometric p as ranking signal (RANK, not FDR-threshold: n is tiny)
    for r in cand:
        r["hyper_p"] = _hyper_p(r["n_overlap"], r["n_library"], n_query)
    cand.sort(key=lambda r: (r["hyper_p"], -r["n_overlap"], r["n_library"]))
    # 3. greedy redundancy collapse on overlap-gene sets
    kept, kept_sets = [], []
    for r in cand:
        s = set(r["overlap_list"])
        redundant = any(
            (len(s | ks) and len(s & ks) / len(s | ks) >= jaccard_max)
            for ks in kept_sets
        )
        if not redundant:
            kept.append(r); kept_sets.append(s)
        if len(kept) >= top_n:
            break
    return kept

# ------------------------------------------------------------------
# Run for Robust x GOBP only
# ------------------------------------------------------------------
genes = queries[SOURCE]
lib   = libraries[TAG]

recs = associate(genes, lib, TAG)                 # raw list (n_overlap>=1)
top  = restrict(recs, n_query=len(genes))

# audit table (kept order, with hyper_p)
pd.DataFrame([{
    "collection":    r["collection"],
    "term":          r["term"],
    "term_id":       r["term_id"],
    "n_library":     r["n_library"],
    "n_overlap":     r["n_overlap"],
    "hyper_p":       r["hyper_p"],
    "overlap_genes": r["overlap_genes"],
} for r in top]).to_csv(
    OUT_TAB / f"{SOURCE}__{TAG}_RESTRICTED.tsv", sep="\t", index=False)

# separate GMTs (do NOT reuse the *_associated_*.gmt names)
n_full = write_gmt(OUT_GMT / f"{SOURCE}__{TAG}_RESTRICTED_fullset.gmt",
                   ((r["term"], r["term_id"] or r["term"], r["library_genes"])
                    for r in top))
n_ovl  = write_gmt(OUT_GMT / f"{SOURCE}__{TAG}_RESTRICTED_overlap.gmt",
                   ((r["term"], r["term_id"] or SOURCE, r["overlap_list"])
                    for r in top))

print(f">>> {SOURCE} {TAG}: {len(recs)} raw -> {len(top)} kept "
      f"(fullset={n_full}, overlap={n_ovl})")
print(">>> table :", OUT_TAB / f"{SOURCE}__{TAG}_RESTRICTED.tsv")
print(">>> gmt   :", OUT_GMT / f"{SOURCE}__{TAG}_RESTRICTED_fullset.gmt")
print(">>> gmt   :", OUT_GMT / f"{SOURCE}__{TAG}_RESTRICTED_overlap.gmt")
print("\nkept terms:")
for i, r in enumerate(top, 1):
    print(f"  {i:2d}. {r['term']}  (n_overlap={r['n_overlap']}, "
          f"p={r['hyper_p']:.2e})  [{r['overlap_genes']}]")

!cp "/content/GSE85718/results" "/content/drive/MyDrive/Dr Uccello/00_Studies/088_NMN_CASES" -r

"""# The End"""